### ISSUE TITLE
Feature request: add album similar recommendation

### ISSUE THREAD

**Issue by hugoperrin** [tamland/python-tidal#102]
The idea is to just add the possibility to use tidal album recommadation for each album.
The tricky part is that it's not available through the same api, so I found a workaround using listen.tidal.com/v1 API instead :)
What do you think about the proposed changes and how to integrate them better?

I have drafted the code for it that works for me locally:
https://github.com/tamland/python-tidal/pull/101

**Comment by morguldir** [comment]
This is available in the 0.7.x branch currently, but there was an endpoint for the similar albums, and one on the listen api, and it supports both.

If you want it in 0.6.x you can do 
```python
session = tidalapi.Session()
session._map_request('albums/%s/similar' % album_id, ret='albums')
```
