### ISSUE TITLE
When is 0.7 coming out?

### ISSUE THREAD

**Issue by BlackLight** [tamland/python-tidal#104]
What's the current state for the 0.7 release?

The new release has been promised for at least two years, PRs on the existing branches has been refused for the same reason, but I don't see anything happening.

mopidy-tidal has been stuck in a limbo for a while waiting for the 0.7 release. The PR I've opened on 0.6 to fix some of the broken/missing things has been rejected because 0.7 was described as "coming soon".

**Comment by tehkillerbee** [comment]
@tamland Are you interested in more maintainers on this project? If you are interested, I would like to assist as a maintainer on github and PyPi. Perhaps @BlackLight would be interested too? Then we can try moving forward on the 0.7 release.

**Comment by morguldir** [comment]
The plan is still a pre-release this month like i said here https://github.com/tamland/python-tidal/pull/99#issuecomment-1133907341

So with the text about pull requests in the README, that was mostly about PR's targeting 0.6.x, a few people have made PR's to the 0.7.x branch, and I've accepted some of them, I haven't been able to prioritize the ones that aren't as major though. That text was written quite a while ago so it doesn't represent the current state that well, but the main point was that making a PR for 0.6.x would be unproductive.

And again you can add `'tidalapi @ git+https://github.com/tamland/python-tidal.git@0.7.x',` to your install_requires in your setup.py, and when you install with pip install -e, it will download from the 0.7.x branch. This is why I haven't done a pre-release before now.

**Comment by BlackLight** [comment]
@morguldir thanks for the update. My PR targeted the 0.6.x branch because I didn't want to mess with the 0.7.x while it was still WIP, nor introduce a dependency on mopidy-tidal side that was still WIP.

If you say that most of the work on 0.7.x is done though (meaning it's just waiting for minor new features + documentation, and no new breaking changes should be introduced), then on mopidy-tidal we can already start using the new branch. What do you think @tehkillerbee? If there aren't many breaking changes in the new version then I could try and put together a PR in these days.

**Comment by tehkillerbee** [comment]
@morguldir Good to hear work is progressing.

@BlackLight I agree, lets switch to the 0.7.x branch if it does not require major changes of mopidy-tidal. I do prefer using PyPi for dependencies if possible, unless we can install a specific 0.7x version (i.e. a specific tag) and not just from the branch.

**Comment by morguldir** [comment]
> @morguldir Good to hear work is progressing. Again, let us know if you are interested in more helping hands on this project. After all, it is the backbone of mopidy-tidal.

Nothing specific, but PR's are welcome, @BlackLight submitted two

> @BlackLight I agree, lets switch to the 0.7.x branch if it does not require major changes of mopidy-tidal. I do prefer using PyPi for dependencies if possible, unless we can install a specific 0.7x version (i.e. a specific tag) and not just from the branch.

You can just do a commit instead of the branch e.g. `tidalapi @ git+https://github.com/tamland/python-tidal.git@53a6661` for 53a6661c7876556e8e45e0efbd1402a4b6d3e105. But the pre-release is still planned for the next few days, so probably not worth updating

Sorry about 454918554b9a1a7b6aba23a459c6654754f503dc by the way, kinda breaking, guess I shouldn't have left that one for so long

Pages support is completed now by the way, along with mixes, moods and genres (old genre endpoints seem to have been deprecated by TIDAL)
