### ISSUE TITLE
0.7.0 Release Plan

### ISSUE THREAD

**Issue by morguldir** [tamland/python-tidal#109]
- [x] 30.06.22 - 0.7.0rc1, first pre-release of the 0.7.x branch
https://pypi.org/project/tidalapi/0.7.0rc1/
- [x] 23.07.22 - Evaluate [dropping python 2.7](https://github.com/tamland/python-tidal/issues/108)
The plan is to drop support https://github.com/tamland/python-tidal/issues/108#issuecomment-1192964104
- [ ] ~~20.07.22 - 0.7.0rc2, second pre-release for additional bug fixes~~ 
Hadn't discovered any bugs, so this won't happen for now.
- [x] 09.09.22 - 0.7.0 release, https://tidalapi.netlify.app/ is updated to 0.7, master is updated with 0.7.x changes
- [ ] 01.06.23 - Evaluate dropping support for the 0.6.x branch
- [ ] 01.01.24 - Most likely drop support for the 0.6.x branch

In the meantime, you can add the branch to your install_requires with `'tidalapi @ git+https://github.com/tamland/python-tidal.git@0.7.x',` if you want to switch before the release. Or use the pre-release on pypi https://pypi.org/project/tidalapi/0.7.0rc1/

**Comment by 2e0byo** [comment]
@tehkillerbee @BlackLight can we close this and drop support for 0.6?  It's been a while.

**Comment by tehkillerbee** [comment]
@2e0byo yep, I think we can safely drop support by now.

**Comment by tehkillerbee** [comment]
Closing as deprecated.
