### ISSUE TITLE
401 Client Error: Unauthorized for url:

### ISSUE THREAD

**Issue by LJAM96** [tamland/python-tidal#111]
Im utilising a integration of tidalapi 0.7.0rc1 with a fork of ultrasonics (Steve-Tech/ultrasonics) and on attempting to utilise the tidalapi I get the error

`tidal - ERROR - 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/sessions?limit=1000`

I'm unaware if this is an issue with the integration or tidalapi, the URL seems to suggest the API keys are over utilised?

**Comment by morguldir** [comment]
This part isn't correct anymore https://github.com/Steve-Tech/ultrasonics/blob/750c2bb0a928eb680913ef238e79422a1a2fb3c9/ultrasonics/official_plugins/up_tidal.py#L98, it was changed in https://github.com/tamland/python-tidal/pull/73

Also note that you need to check the return status of the load_oauth_session, there's no point in continuing if the session wasn't loaded

**Comment by LJAM96** [comment]
Ah thank you, thats great! 
Apologies, based on the URL I thought initially it would be an API being over utilised and not the program using it

**Comment by TinkeringTony** [comment]
> Im utilising a integration of tidalapi 0.7.0rc1 with a fork of ultrasonics (Steve-Tech/ultrasonics) and on attempting to utilise the tidalapi I get the error
> 
> `tidal - ERROR - 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/sessions?limit=1000`
> 
> I'm unaware if this is an issue with the integration or tidalapi, the URL seems to suggest the API keys are over utilised?

Were you able to get it working? I'm running into the same problem and very new to python/api's.

**Comment by morguldir** [comment]
https://github.com/XDGFX/ultrasonics/pull/45#issuecomment-1242640666
