### ISSUE TITLE
Question: Genre of a track

### ISSUE THREAD

**Issue by zaptrem** [tamland/python-tidal#115]
How do I get the genre of a track? Thanks

**Comment by eejd** [comment]
I can't determine from the API documentation or what I can see without tracing the parsing to determine if the genre of a track or album is exposed on the Tidal side or if the (now deprecated) Genre option for searching via genre is the only way to access genre-track relationships. I would simply like to be able to get the genre along with a track name/info from a playlist.

**Comment by tehkillerbee** [comment]
You are correct, there are no way through the API to get the genre of a track

I just took a look at the Tidal web player. Maybe I am wrong but as far as I see, there is no "Genre" field for a given track. So I see no way we can add this functionality.

**Comment by tehkillerbee** [comment]
Closed as Tidal does not provide this functionality. Feel free to reopen, if you find a way to do it.
