### ISSUE TITLE
Feature: support playlist edits.

### ISSUE THREAD

**Issue by 2e0byo** [tamland/python-tidal#116]
Currently there is no support for moving items in playlists, inserting, or bulk actions.

From a comment on [this pr](https://github.com/tehkillerbee/mopidy-tidal/pull/76):
> a first look at the call made by the Tidal client shows a POST request to the playlist item URL with the toIndex argument

looks promising.  I wonder if `toIndex` would let additions work as insertions?  In any case it would be nice to support:

- [x] moving tracks
- [x] inserting at given index
- [x] bulk actions (if the backend api supports it)

These (particularly the first two) would be very handy in mopidy-tidal.

I guess it's a matter of spinning up MITMProxy again...

**Comment by tehkillerbee** [comment]
@2e0byo FYI, some of this functionality is already implemented in tidal2: https://github.com/arnesongit/plugin.audio.tidal2
