### ISSUE TITLE
Question about client secret

### ISSUE THREAD

**Issue by grangej** [tamland/python-tidal#119]
How did you obtain the client secret for this project?

**Comment by 2e0byo** [comment]
Whilst I don't know the answer to this question as I didn't do it, tidalapi is unofficial, i.e. reverse-engineered.  Everything in it was obtained by reverse engineering.  It exists to allow people with subscriptions to use tidal in free (open) music players, not to bulk-download aka steal.  But if we go posting 'how to get client secret' articles, (i) the method probably won't work for long and (ii) people will probably use it for ends we don't support, i.e. stealing. This is why we don't (and won't) post this kind of information.
