### ISSUE TITLE
Can't get track info

### ISSUE THREAD

**Issue by davigamer987** [tamland/python-tidal#120]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidal.com/v1/tracks/%3Ctidalapi.media.Track%20object%20at%200x7f072ff101c0%3E?sessionId=&countryCode=BR&limit=1000

(Removed session id for privacy)

The code i tried with is:
    search_query = str(search_query)
    results = session.search(query=search_query, models=[tidalapi.media.Track])
    print(results)
    defined = results.get("top_hit")
    session.track(defined)
    track = tidalapi.Track
    print(track)
    print(track.name)
    print(track.duration)
    
    
 This happens with every track i try so i don't think it's region related (And i can access this just fine in the tidal app)

**Comment by tehkillerbee** [comment]
Can you check if this is indeed still an issue? Also please include a more detailed error log.

**Comment by arsaboo** [comment]
I am getting the same error. However, it is a little weird. 
In Jupyter notebook, `session.track(176834458)` works and returns `<tidalapi.media.Track at 0x19883dc45b0>`. 

However, the same does not work in the function that I have here. 
https://github.com/arsaboo/beets-tidal/blob/4d7e4ebc43e5ddc4ad99c7f1f667f6fccea34ef9/beetsplug/tidal.py#LL142C39-L142C39

Here's the error:
```bash
tidal: Processing 1/36 tracks - Amrita Singh - Pagglait (Original Motion Picture Soundtrack) - Pagglait
HTTP error on 404
tidal: Track not found: 176834458. Error: 404 Client Error: Not Found for url: https://api.tidal.com/v1/tracks/%3Cbuilt-in%20function%20id%3E?sessionId=XYZ&countryCode=US&limit=1000
```
Let me know if I can provide any additional information/logs.

**Comment by tehkillerbee** [comment]
> I am getting the same error. However, it is a little weird. In Jupyter notebook, `session.track(176834458)` works and returns `<tidalapi.media.Track at 0x19883dc45b0>`.
> 
> However, the same does not work in the function that I have here. https://github.com/arsaboo/beets-tidal/blob/4d7e4ebc43e5ddc4ad99c7f1f667f6fccea34ef9/beetsplug/tidal.py#LL142C39-L142C39
> 
> Here's the error:
> 
> ```shell
> tidal: Processing 1/36 tracks - Amrita Singh - Pagglait (Original Motion Picture Soundtrack) - Pagglait
> HTTP error on 404
> tidal: Track not found: 176834458. Error: 404 Client Error: Not Found for url: https://api.tidal.com/v1/tracks/%3Cbuilt-in%20function%20id%3E?sessionId=XYZ&countryCode=US&limit=1000
> ```
> 
> Note that other things work in that plugin (so it is not an authentication issue).
> 
> Let me know if I can provide any additional information/logs.

Based on the garbled URL in the error you provided and on the sources, this looks like a wrong id is passed to self.session.track in both cases.

In essence, ID must be a number not a Track object or string. Closing, as this is not a tidalapi issue
