### ISSUE TITLE
Automate Login for make script in PythonAnywhere?

### ISSUE THREAD

**Issue by 9acca9** [tamland/python-tidal#122]
Hi, there is a way i can automate the login? (i mean, that there is no need to "click" in a link?), for avoid the need of user interaction. In that way i can put my script in PythonAnywhere and run that every x time.
Is possible?

Thanks!

**Comment by tehkillerbee** [comment]
See the method we use here:
https://github.com/tehkillerbee/mopidy-tidal/blob/552de8529bce1a5950c02086a0c914959585c2ad/mopidy_tidal/backend.py#L77

**Comment by 2e0byo** [comment]
Logging in requires a user tok
