### ISSUE TITLE
load_oauth_session() not working correctly

### ISSUE THREAD

**Issue by Harvara** [tamland/python-tidal#123]
The load_oauth_session method doesn't work for me, I always get an 401.
I tired it with the login_oauth_simple() and it works without a problem. But I want to run it in a headless system, so I need to persist the credentials. I used the tokens extracted from my files (android app) as well as the ones I retrieved via the login_oauth_simple() method.

I debuged load_oauth_session further down and found, that the request against the /v1/sessions endpoint does not provide any auth data. 

They are set in the session class (Lines 270-273) but the request doesn't use them. The request send in requests.py has empty request_params, no data and an empty header.

Is this a bug or am I missing something?

You can see how I tried to connect in my Spotify2Tidal repo.

**Comment by tehkillerbee** [comment]
Have you tried the same approach as we use with mopidy-tidal?

**Comment by tehkillerbee** [comment]
Closing due to no updates.
