### ISSUE TITLE
I can get client id?

### ISSUE THREAD

**Issue by 9acca9** [tamland/python-tidal#125]
I dont see nothing related in the docs.
Thanks!

**Comment by d4kine** [comment]
Well, it's visible in the code :) You can print it out via `session.config.client_id`

```py
tidal = tidalapi.Session()
tidal.login_oauth_simple()
# proceed login in browser 
print('access_token: '+ tidal.access_token)
print('client_id: '+ tidal.config.client_id)
print('client_secret: '+ tidal.config.client_secret)
```

@tamland you can close this issue

**Comment by 2e0byo** [comment]
tidalapi does not provide an api to retrieve the client id.
