### ISSUE TITLE
Fetch Album Credits

### ISSUE THREAD

**Issue by lsidorki** [tamland/python-tidal#126]
Hello,

I have checked the API, but could not find any way to get the Album Credits. What I mean by this, is:
https://listen.tidal.com/album/_id/credits (for instance: https://listen.tidal.com/album/150379405/credits )
It contains tons of additional information, like Composer, Lyricist, Producer, Director, Mastering Engineer, etc.
Could this feature be added as well to the API? Or am I missing something?

Best Regards,
Lukas

**Comment by tehkillerbee** [comment]
Currently, this does not appear to be available, sorry.

But PRs are welcome to add this functionality.

**Comment by tehkillerbee** [comment]
Closing, as there seem to be no way to get this information at the moment.
