### ISSUE TITLE
login failed - got key error 'picture'

### ISSUE THREAD

**Issue by m0555** [tamland/python-tidal#129]
Hi,
Today I can not login anymore and got a key error 'picture' on login
could it be, that Tidal has removed picture_id from user account?

I tryed to comment out line 77 in user.py `self.picture_id = json_obj['picture']` and that works.

Thanks
Marc

**Comment by frogleon** [comment]
I'm also facing same issue, I had to make it 

```python
self.picture_id = json_obj['picture'] if 'picture' in json_obj else ''
```

**Comment by Lauravdsanden** [comment]
> Hi, Today I can not login anymore and got a key error 'picture' on login could it be, that Tidal has removed picture_id from user account?
> 
> I tryed to comment out line 77 in user.py `self.picture_id = json_obj['picture']` and that works.
> 
> Thanks Marc

How did you comment this out when using the API?

**Comment by m0555** [comment]
> How did you comment this out when using the API?

For me (on windows 10) the path to tidalapi is:
 C:\Users\myusername\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidalapi, 
but maybe there is another location depending of your installation
Edit the file user.py
comment out line 77
`# self.picture_id = json_obj['picture']`
and add the line:
`self.picture_id = json_obj.get('picture', '')`

**Comment by Lauravdsanden** [comment]
> > How did you comment this out when using the API?
> 
> For me (on windows 10) the path to tidalapi is: C:\Users\myusername\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidalapi, but maybe there is another location depending of your installation Edit the file user.py comment out line 77 `# self.picture_id = json_obj['picture']` and add the line: `self.picture_id = json_obj.get('picture', '')`

I'm using Google Colaboratory so I don't know where the file would be located. Any idea how to do this there?

**Comment by m0555** [comment]
> I'm using Google Colaboratory so I don't know where the file would be located. Any idea how to do this there?
I'm not familiar with Google Colab, but maybe you could fork/edit tidalapi at github and Google Colab let you install your own version until the original library is fixed?

**Comment by Lauravdsanden** [comment]
I'm just going to run it locally now until it's fixed

**Comment by LynxWall** [comment]
same issue here on raspberry pi, commented out line 77 to get it working. Wish I would have seen this sooner :)
Will wait for next release instead of using fork.
