### ISSUE TITLE
Incomplete track info

### ISSUE THREAD

**Issue by VikasRana** [tamland/python-tidal#132]
`for track in tracks:
    print(track.name)`

Doesn't print what's within ( & ) if they are present in a track.

E.g. `Bringing Me Down (Boxplot Remix)` would be printed as `Bringing Me Down` only.

**Comment by VikasRana** [comment]
Is there a way to get the desired result? Maybe I'm missing something.

**Comment by tehkillerbee** [comment]
Looks like a bug. Can you provide an example track/album we can use to investigate further?

**Comment by VikasRana** [comment]
https://listen.tidal.com/album/284478051

**Comment by tehkillerbee** [comment]
@VikasRana That information is available in `track.version`. Eg.
```
print(track.name)
print(track.version)
```

**Comment by tehkillerbee** [comment]
Closing as completed.
