### ISSUE TITLE
Append track version info to name. 

### ISSUE THREAD

**Issue by tehkillerbee** [tamland/python-tidal#139]
As mentioned in #132, track version info may not be a part of track name. This means the track name does not (always) correspond with the track name displayed by tidal. 

Currently user must append the track version info manually. Therefore, we should add a way to get the full name as shown in the Tidal player.

1. Track name should automatically have track version info appended, if it exists. I have not checked but its likely that the version field is empty. 
2. Add a separate "track full name" variable that can be used for this purpose.

Any alternative solutions are welcome. 

FYI, In the before mentioned issue, it appears that /some/ tracks already has the version info added to the name.. If this is indeed the case, this means we cannot blindly append track version to the name.... Oh well.

**Comment by WilliamGuisan** [comment]
Interestingly, this is also apparent on listen.tidal.com and the apps, too. The track version info seems to always be shown in the player and in the list under "Title" (Favorites, Playlist etc) but not when making the player big. Track version number also isn't visible in a songs "Credits".

![Screenshot from 2023-06-06 11-57-24](https://github.com/tamland/python-tidal/assets/135181837/97d6bb1c-5832-45d6-9cdd-56138c1c0120)

**Comment by WilliamGuisan** [comment]
I forked this repo (first time using git, very exciting :D) and added a 'full_name' variable to the media.Track() class which combines 'name' and 'version' in case 'version = None'.
It seems to work thus far, but i am a bit scared of opening a pull request, don't wan't to mess up things :0
So if anyone wants to look over those changes, you are more than welcome :)

**Comment by tehkillerbee** [comment]
Hello @WilliamGuisan and thanks for the contribution! 

Feel free to make a PR (nothing to mess up!) , then we will review your additions :)

**Comment by tehkillerbee** [comment]
Fixed in #142
