### ISSUE TITLE
MQA

### ISSUE THREAD

**Issue by JuniorJPDJ** [tamland/python-tidal#14]
Are you going to add this quality?

**Comment by JuniorJPDJ** [comment]
MQA is available as Master quality.

**Comment by morguldir** [comment]
Actually it wasn't working yet, i wrote that  it wasn't implemented in the source code, but i hadn't put it in the docstring.

Anyway, with 7286cbf29a87c6f5dcd19f63aafcd9ee3d1bdb8b, get_url() will return a master quality track if you have the right subscription and have the quality set  to master. Note that you have to log in again if you want get master quality tracks, as older logins will just return a HiFi/Lossless track.

**Comment by JuniorJPDJ** [comment]
It worked before oAuth update then ;D
Thanks for your good work!
