### ISSUE TITLE
The API doesn't return the correct number of favorites

### ISSUE THREAD

**Issue by dgiglio** [tamland/python-tidal#143]
Hi,
I'm playing with the APIs and I've noticed that I cannot extract the full set of my favourite artists. I've compared the cardinality of the set returned by my code with one from a service as, i.e. Soundiiz and the latter is significantly bigger.

However, my code is very simple:

        def getFavouriteArtists(self):
        lartists = []
        subset = []
        page = 1000
        offset = 0

        subset = tidalapi.user.Favorites(self.session,XXXXXXXXX).artists()
        lartists = subset

        while len(subset) == page:
            offset += page
            subset = tidalapi.user.Favorites(self.session,XXXXXXXXX).artists(page, offset)
            lartists.extend(subset)

        return lartists

I know that each call has a paging limit of 1000, so I make a first call and I check its result set size, if it matches the paging limit it's very likely I have to iterate further, and I keep doing until I get a smaller set, then the function returns.

Moreover, I get the wrong result at the very fist call (the total is less than 1000 items) so it looks like the issue lies elsewhere.

Any clue?
Thanks in advance.

**Comment by dgiglio** [comment]
> Sadly i can't make out any other issues, since I can not recreate the problem :/

Hi, WIlliam
first of all, thanks for your reply. I'll investigate further and try to collect more informations.
Best regards.
--
Daniele

**Comment by tehkillerbee** [comment]
Since there has been no updates, I will close this issue. Feel free to reopen if necessary.
