### ISSUE TITLE
Handle optional user fields gracefully

### ISSUE THREAD

**Issue by tehkillerbee** [tamland/python-tidal#148]
Optional/removed fields often breaks tidalapi. We should handle optional/unused fields gracefully

See this issue for more details:
https://github.com/tamland/python-tidal/pull/147

**Comment by 2e0byo** [comment]
FWIW I think we should only get the fields we actually use, and then just provide the raw response object to anyone who wants it.  Or if we still want to parse, something like:

```python
for k, v in response.items():
   if not hasattr(self, k):
       setattr(self, k, v)
```
