### ISSUE TITLE
Tidal no longer includes gender attribute for user user object

### ISSUE THREAD

**Issue by HenryKautz** [tamland/python-tidal#159]
Tidal no longer includes gender attribute for user user object.  

  File "/Users/kautz/opt/anaconda3/envs/henry/lib/python3.11/site-packages/tidalapi/user.py", line 114, in parse
    self.gender = json_obj["gender"]
                  ~~~~~~~~^^^^^^^^^^
  KeyError: 'gender'

In class LoggedInUser(FetchedUser), remove line:

self.gender = json_obj["gender"]

**Comment by nawordar** [comment]
This is already fixed on master

**Comment by tehkillerbee** [comment]
Yes, this is already fixed. Please install latest version of tidalapi from git until we release the next version to PyPi
