### ISSUE TITLE
Showing track artist

### ISSUE THREAD

**Issue by JanuszBIznesu1** [tamland/python-tidal#163]
Hi!

I'm using this:

https://github.com/bkr32/Tidal-Account-Data-Transfer

I was modify a little, code to show missing tracks which can't be transferred. 

But how can i get showing artist of missing track? For now i can have only track title. 
And also i don't want to need click enter every error, but on finish.

Here is my code:

```python
import tidalapi
from tqdm import tqdm

session = tidalapi.Session()
print('Enter your credentials for the account you want to transfer from')
session.login_oauth_simple()
uid = session.user.id
TidalUser = tidalapi.Favorites(session, uid)
tracks = TidalUser.tracks()

session2 = tidalapi.Session()
print('Enter your credentials for the account you want to transfer to')
session2.login_oauth_simple()
uid2 = session2.user.id
TidalUser2 = tidalapi.Favorites(session2, uid2)

print('Copying ...')
for i in tqdm(range(len(tracks))):
    try:
        TidalUser2.add_track(tracks[i].id)
    except:
        print('Skipped', tracks[i].full_name)
        input("Press Enter to exit...")
``` 
![Zrzut ekranu (1063)](https://github.com/tamland/python-tidal/assets/54276954/e9e1611f-62e8-490b-838b-d6ddf362b0a6)

**Comment by 2e0byo** [comment]
`Track` inherits from `Media` and thus has `.artists` and `.artist`.  See [the docs](https://tidalapi.netlify.app/api.html#tidalapi.media.Media) for `Media` here.

In general to find this kind of thing out, use `dir`, `inspect`, `??` (in IPython) or, my favourite `rich.inspect` (install rich first and then `from rich import inspect`) in an interactive shell.  In this case you'd want to inspect e.g. `tracks[0]` to see what attributes and methods it has.

**Comment by JanuszBIznesu1** [comment]
```python
print('Copying ...')
for i in tqdm(range(len(tracks))):
    try:
        TidalUser2.add_track(tracks[i].id)
    except:
        print('Skipped', tracks[i].full_name, 'by' , tracks[i]artist)
        input("Press Enter to exit...")
``` /

**Comment by JanuszBIznesu1** [comment]
This is how it working now:

![artist](https://github.com/tamland/python-tidal/assets/54276954/974a8b45-c38c-4b19-b559-d089107d032b)

**Comment by JanuszBIznesu1** [comment]
Here is my code:

```python
print('Copying ...')
for i in tqdm(range(len(tracks))):
    try:
        TidalUser2.add_track(tracks[i].id)
    except:
        print('Skipped', tracks[i].full_name, 'by' , tracks[i].artist)
        input("Press Enter to exit...")
```

**Comment by JanuszBIznesu1** [comment]
Edit:
I do it and it works.

```python
print('Copying ...')
for i in tqdm(range(len(tracks))):
    try:
        TidalUser2.add_track(tracks[i].id)
    except:
        print('Skipped', tracks[i].full_name, 'by' , tracks[i].artist.name)
        input("Press Enter to exit...")
``` 

![final](https://github.com/tamland/python-tidal/assets/54276954/249381b5-8ae5-4c10-b13a-8ff654fd6e2a)

**Comment by 2e0byo** [comment]
Yes.  The string you saw earlier was the result of calling `repr(Artist)` (called by `print` when it formats its output).  To see the attributes you need an inspection tool (or to read the docs).  I recommend spending a while in an interactive shell (python/ipython) to get used to the api of `python-tidal`.

**Comment by JanuszBIznesu1** [comment]
> Yes. The string you saw earlier was the result of calling `repr(Artist)` (called by `print` when it formats its output). To see the attributes you need an inspection tool (or to read the docs). I recommend spending a while in an interactive shell (python/ipython) to get used to the api of `python-tidal`.

Now it's working as i wanted.

**Comment by tehkillerbee** [comment]
This is a cool example of what tidalapi can be used for. Perhaps we should add a folder with examples.

**Comment by JanuszBIznesu1** [comment]
In tidal api there is also limit track which can be transferred between accounts. In factory it's 1000 but i changed it to 9999.

I can't edit files in fork of https://github.com/bkr32/Tidal-Account-Data-Transfer but here [https://drive.google.com/file/d/1ltZBpewujBNXXP9vqizB9vSjAJxNk7Sx/view?usp=sharing](url) is my edited codes to showing missed tracks name and artist for example when one account has regional restrictions. I also added os.system("pause") so that the window does not close automatically when the transfer is complete and you could check which music is missing. Also i added script to transfer playlists.

This changes i made only in albums and tracks.
