### ISSUE TITLE
question about tracks

### ISSUE THREAD

**Issue by Dialgatrainer02** [tamland/python-tidal#166]
how can i read the list of tracks that a user has saved into their collection eg the ones found here https://listen.tidal.com/my-collection/tracks? 
 i have looked though the docs and other examples and i cant seem to find anything

**Comment by bennetrr** [comment]
You can do that by calling

```python
Session.user.favorites.tracks()
```

**Comment by Dialgatrainer02** [comment]
thanks this is exactly what i needed
