### ISSUE TITLE
Getting image of artist fails

### ISSUE THREAD

**Issue by bennetrr** [tamland/python-tidal#167]
When calling `Artist.image(750)`, I get following exception:

```python
 File "/Users/wemogymac/projects-bennetr/weckpi/src/coreplugin/src/weckpi/plugin/coreplugin/music/media_providers/tidal.py", line 103, in <listcomp>
    image=x.image(750)
          ^^^^^^^^^^^^
  File "/Users/wemogymac/Library/Caches/pypoetry/virtualenvs/weckpi-coreplugin-YPARpiOD-py3.11/lib/python3.11/site-packages/tidalapi/artist.py", line 180, in image
    self.picture.replace("-", "/"),
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

`x` is an `Artist` object I got from calling `Session.search('')['artists']`.

As far as I can tell, getting the image works for Playlists and Tracks.

When I open TIDAL in my browser and look in the devtools, I can see a request to the `/artist` endpoint, whose response contains a picture id. In the `Artist.image()` function, the endpoint `/artists` is requested instead. Could be this the issue?

**Comment by tehkillerbee** [comment]
Good catch. I did notice that the artist image stopped working in the latest release, but I was nolr sure if this was due to a change by tidal. 

You are welcome to test if changing the endpoint to /artist does indeed fix the issue (PR is also very welcome) , otherwise we will look into this ASAP.

**Comment by bennetrr** [comment]
Thanks for your very quick response.

I was mistaken, the TIDAL web app seems to use a different API. Requesting `/artist` just results in a 404.
I will try to figure out what the problem is later this day.

**Comment by bennetrr** [comment]
In a way related to this, is it possible to add a `Developement.md` to the repo, that describes how / where someone can find information about TIDAL's API?

**Comment by tehkillerbee** [comment]
> In a way related to this, is it possible to add a `Developement.md` to the repo, that describes how / where someone can find information about TIDAL's API

Documentation about the (reverse engineered) tidalapi is currently available here:
https://tidalapi.netlify.app/

**Comment by tehkillerbee** [comment]
Returning artist image directly from tidalapi does seem to work, although certain frontends such as Mopidy-Iris still has problems, which is where I first noticed the issue.

Make sure you get the image URL as such:
```python
...
artist.image(750)
```

In https://github.com/tamland/python-tidal/pull/174, I have added a default dimension now to avoid having to set the dimension manually. Then the image can be returned as such:
```python
...
artist.image()
```

**Comment by bennetrr** [comment]
Hmm, still doesn't work for me. I get the same exception again, with a resolution of 750.

**Comment by tehkillerbee** [comment]
Perhaps there is no artist image associated with this specific artist? Have you tested with a different one?

**Comment by bennetrr** [comment]
> Perhaps there is no artist image associated with this specific artist?

That's the problem. I didn't think of it until now, but both artists I searched for have collaborations which are also listed under artists. These collaborations do not have images, and that's why the exception is thrown.

Now my question is, why is the exception below not thrown?

https://github.com/tamland/python-tidal/blob/5b0023ce209394b670760a9f0b3bcd9723cdff58/tidalapi/artist.py#L213-L217

**Comment by tehkillerbee** [comment]
[#171](https://github.com/tamland/python-tidal/pull/171) has now been merged. Closing this issue.
