### ISSUE TITLE
Quality "HIGH" for HiRes-FLAC from August 2023? 

### ISSUE THREAD

**Issue by unwan878** [tamland/python-tidal#172]
TIDAL has announced to change from MQA to HiRes-FLAC starting in August 2023.
Would you please implement downloading HiRes-FLAC "HI_RES_LOSSLESS" files?

**Comment by tehkillerbee** [comment]
Yep, I am currently working on adding support for this.

**Comment by tehkillerbee** [comment]
It turns out very little was needed to add support for HI_RES. I have added a couple of helper functions to allow setting the quality manually, otherwise it will use HIGH per default.
```python
import tidalapi

session = tidalapi.Session()
# Will run until you visit the printed url and link your account
session.login_oauth_simple()
# Override the required playback quality, if necessary
# session.set_audio_quality(Quality.lossless)
# session.set_audio_quality(Quality.master)

album = session.album(66236918)
tracks = album.tracks()
for track in tracks:
    print(track.name)
    for artist in track.artists:
        print(' by: ', artist.name)
```
