### ISSUE TITLE
get_url AttributeError: 'str' object has no attribute 'session'

### ISSUE THREAD

**Issue by Dialgatrainer02** [tamland/python-tidal#177]
i get this error runing get_url()
Media.Track.get_url(track.name)
  File "/home/olivia/tidalapi/venv/lib/python3.11/site-packages/tidalapi/media.py", line 196, in get_url
    "audioquality": self.session.config.quality,
                    ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'session'                                           
im a noob at python i have session defined as session = tidalapi.Session() but it doesnt work and im unsure what to do

**Comment by tehkillerbee** [comment]
Can you please include the full code that you are trying to execute? Then it is easier to help.

**Comment by Dialgatrainer02** [comment]
yes sure 
`import tidalapi
import os

session = tidalapi.Session()
Media = tidalapi.media


class Session(tidalapi.Session):
    def __init__(self):
        super().__init__()

    def easy_login(self):
        if not os.path.exists("token.txt"):
            self.login_oauth_simple()

            with open("token.txt", "w") as f:
                f.write(
                    f"{self.token_type}\n{self.access_token}\n{self.refresh_token}\n{self.expiry_time}"
                )
        else:
            with open("token.txt", "r") as f:
                token_type = f.readline().strip()
                access_token = f.readline().strip()
                refresh_token = f.readline().strip()
                expiry_time = f.readline().strip()

            self.load_oauth_session(
                token_type, access_token, refresh_token, expiry_time
            )


if __name__ == "__main__":
    session = Session()
    session.easy_login()

user_tracks = session.user.favorites.tracks()
for track in user_tracks:
    Media.Track.get_url(track.name)
    print(track.name)
print('###############################################################')
user_album = session.user.favorites.albums()
for album in user_album:
   print(album.name)
   Media.Track.get_url(album.name)`

**Comment by tehkillerbee** [comment]
Well there are several things wrong with your code, but as a starting point, get_url() is used wrong. Instead, you should use it similarly to track.name;
```
print(track.name)
print(track.get_url())
```

You can use this example to get you started:

```python

import logging
import json
from pathlib import Path
import sys

import tidalapi

logger = logging.getLogger(__name__)

oauth_file = Path("tidal-oauth.json")


class TidalapiExample:
    def __init__(self):
        self._active_session = tidalapi.Session()

    def _save_oauth_session(self, oauth_file: Path):
        # create a new session
        if self._active_session.check_login():
            # store current OAuth session
            data = {}
            data["token_type"] = {"data": self._active_session.token_type}
            data["session_id"] = {"data": self._active_session.session_id}
            data["access_token"] = {"data": self._active_session.access_token}
            data["refresh_token"] = {"data": self._active_session.refresh_token}
            with oauth_file.open("w") as outfile:
                json.dump(data, outfile)
            self._oauth_saved = True

    def _load_oauth_session(self, **data):
        assert self._active_session, "No session loaded"
        args = {
            "token_type": data.get("token_type", {}).get("data"),
            "access_token": data.get("access_token", {}).get("data"),
            "refresh_token": data.get("refresh_token", {}).get("data"),
        }

        self._active_session.load_oauth_session(**args)

    def _login(self):
        try:
            # attempt to reload existing session from file
            with open(oauth_file) as f:
                logger.info("Loading OAuth session from %s...", oauth_file)
                data = json.load(f)
                self._load_oauth_session(**data)
        except Exception as e:
            logger.info("Could not load OAuth session from %s: %s", oauth_file, e)

        if not self._active_session.check_login():
            logger.info("Creating new OAuth session...")
            self._active_session.login_oauth_simple()
            self._save_oauth_session(oauth_file)

        if self._active_session.check_login():
            logger.info("TIDAL Login OK")
        else:
            logger.info("TIDAL Login KO")
            raise ConnectionError("Failed to log in.")

    def run(self):
        # do login
        self._login()

        #album = self._active_session.album(110827651)  # Lets Rock (LOSSLESS, HIRES_LOSSLESS, MQA)
        #print(album.name)
        #print(album.image(640))
        #tracks = album.tracks()

        tracks = self._active_session.user.favorites.tracks()
        for track in tracks:
            print(track.name)
            # for artist in track.artists:
            #    print(' by: ', artist.name)
            try:
                print(track.get_url())
            except:
                continue

if __name__ == "__main__":
    TidalapiExample().run()
```

**Comment by Dialgatrainer02** [comment]
thank you this is my first true attempt at python and the help is greatly appreciated 
this code works but gets rate limited so ill add timers and continue from there

**Comment by tehkillerbee** [comment]
No problem, we all have to start somewhere and there is always something new to learn :)

I'd like to have proper examples in place for tidalapi to make it easier to users to get started - and to contribute with their own scripts.
