### ISSUE TITLE
Add support for "free" subscription.

### ISSUE THREAD

**Issue by curiousercreative** [tamland/python-tidal#178]
I'm able to browse the catalog, but unable to play any track. The web player seems to be using an mpeg-dash stream and it seems there has been some discovery done over here: https://github.com/FUMR/tidal-async/issues/53

Originally reported on Mopidy-Tidal: https://github.com/tehkillerbee/mopidy-tidal/issues/128

**Comment by 2e0byo** [comment]
For the sake of completeness, there's an argument *against* supporting this: Tidal are doubtless aware of these 3rd party libraries.  I doubt they're particularly happy about them, but so long as we require users to pay, we're not much of a commercial problem (in fact I think we're the opposite: I wouldn't use tidal if not for tidalapi).*  They want casual users in their player, with their branding, ads, etc.  But tidalapi users have *already* paid; and probably care enough to hang around.  If Tidal ever got cross with this project and reached out (unlikely) we'd have a pretty good argument.

Does this matter to us?  We're out to help people use tidal (in novel ways) not to help tidal's business model.  But I think the argument is worth thinking about.  mopidy-spotify made a similar decision back in the day; I don't know, but I presume for similar reasons.

@tehkillerbee @curiousercreative thoughts?

*There's piracy, but that's not particularly relevant here given that the free tier is for lossy music already widely available.

**Comment by tehkillerbee** [comment]
One issue is adding support when the "free" subscription is not available everywhere (it is currently not available in Denmark) so it requires a VPN.

>  I doubt they're particularly happy about them, but so long as we require users to pay, we're not much of a commercial problem (in fact I think we're the opposite: I wouldn't use tidal if not for tidalapi).

This is a good point that I did not think about. I think it makes sense only to support paid subscriptions.

**Comment by curiousercreative** [comment]
Sure, that's fair. So this should be closed as "will not support"?

**Comment by tehkillerbee** [comment]
Yes, for now we will close this as a wont-fix
