### ISSUE TITLE
Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=4zx46pyr9o8qZNRw

### ISSUE THREAD

**Issue by richstokes** [tamland/python-tidal#19]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=4zx46pyr9o8qZNRw

^ When following the example?

Are we supposed to generate our own token? Doesnt seem to be any reference to this in the docs

**Comment by morguldir** [comment]
Just to make sure, you are replacing "username" and "password" with your own account details right?

Otherwise, make sure that you are using your username and the correct password. Also, what is your subscription type?

**Comment by richstokes** [comment]
Yep, using my own user and password - they let me log in to the app/website OK.

Lossless/Hi-Fi subscription

**Comment by morguldir** [comment]
You didn't set the quality, which makes it use an api token with less permissions, which isn't compatible with your subscription, although that shouldn't be needed to login. 

Feel free to reopen if you are still having issues.

**Comment by richstokes** [comment]
How do you set the quality? There's no info on that on the readme/docs?

**Comment by richstokes** [comment]
Nevermind - i just tried again with the latest code and can login now!

**Comment by sorenwacker** [comment]
I have the same issue. Where can I see my subscription status? I just signed up.
