### ISSUE TITLE
Favourites has no mixes() function to get the favourite mixes

### ISSUE THREAD

**Issue by Nokse22** [tamland/python-tidal#197]
I checked the website and it is possible to see the favourite mixes and radios at https://listen.tidal.com/my-collection/mixes

Also adding/removing a mix from the favourite is not possible

**Comment by tehkillerbee** [comment]
> I checked the website and it is possible to see the favourite mixes and radios at https://listen.tidal.com/my-collection/mixes

It seems you are right, mixes seem to be missing from favorites.

Feel free to add a PR, otherwise this will be added as soon as possible.

**Comment by Nokse22** [comment]
I tried to add this feature myself, but I think it's not possible for now.
I tried to just do it the same way as the others, but it doesn't work. So I tried to see what requests the website made.

To get the favourite mixes it does:
`https://listen.tidal.com/v2/favorites/mixes?offset=0&limit=50`

instead for example for the albums it does:
`https://listen.tidal.com/v1/users/12345678/favorites/albums?offset=0&limit=50`

**Comment by tehkillerbee** [comment]
After looking further into this issue, it seems we already have a partial functionality for getting mixes found in your collection. 
```
mixes = self._active_session.mixes()
```

Anyways, this does not currently work (for me, this page is just empty). Perhaps for legacy purposes?

As you correctly point out, using the same approach as albums does not work as expected. But if you use the web player to get favourite albums / mixes, you will notice that both of them use the v2 URL for the GET method. The python-tidal API was probably reverse engineered using an earlier version.

Perhaps it is possible to get the correct path to the mixes endpoints, using the v1 URL instead. Or perhaps the mixes endpoint does not exist for v1 - only v2?

**Comment by jozefKruszynski** [comment]
After doing some exploratory testing, it's definitely possible to get the mixes from favourites.
It requires a few minor changes here and there, including the use of a v2 url, but the change for that is also minimal.
I'l try to add a PR in a couple of days.

**Comment by tehkillerbee** [comment]
> After doing some exploratory testing, it's definitely possible to get the mixes from favourites. It requires a few minor changes here and there, including the use of a v2 url, but the change for that is also minimal. I'l try to add a PR in a couple of days.

Great to hear you found a solution. Perhaps we should consider using v2 links elsewhere in tidalapi.

**Comment by jozefKruszynski** [comment]
I ended up having to create a MixV2 class as the structure is different enough to warrant it, however, this structure is only used for this one v2 api endpoint, and tidal themselves in their web app use the v1 api for every other call related to mixes.

It's a rather odd situation as you need to use the v2 endpoint to return a list of something that you then actually only ever need the name and ID of really.

I'll push a draft PR to make what I'm talking about a bit more tangible.

**Comment by tehkillerbee** [comment]
@jozefKruszynski Great to hear you found a solution.

Great to hear you found a solution. I'll test this out and get it merged ASAP so we can get this feature in for the next release.

**Comment by tehkillerbee** [comment]
Fixed in #207 . Merged into master today, will be added to next release asap.
