### ISSUE TITLE
Tidal now has a public official API

### ISSUE THREAD

**Issue by vaosilva** [tamland/python-tidal#199]
Just passing by to leave the note that Tidal now has
> "a subset of our Web API available to developers outside Block and TIDAL for beta testing"
@ https://developer.tidal.com/blog/welcome-to-tidal-developer

This was hinted a while ago at the AMA Reddit thread hosted by Tidal's CEO, and the rollout has started this week.

Honestly I don't know how much the official endpoints differ from the ones used by this package, but since - and if my judge does not fail me - the ones used here are took from analysis of the requests of the web client, and their usage may be against the ToS, eventually the better step from now on would be to proceed with the substitution of the unofficial requests with their counterparts which are made available officially by Tidal's API.

I don't know if Tidal is gonna invest on a SDK of their own, wrapping their API in some shape or form, but since it took them 8 years to open their doors to developers, I believe that this project still deserves focus and maintenance, updating it with what is now at public disposal. Hell, maybe it even gets a mention on their docs as a recommended Python wrapper. :)

**Comment by tehkillerbee** [comment]
@vaosilva Definitely an exciting development. I do believe the existing API does not support any playback, however.

**Comment by vaosilva** [comment]
Yes, hence the choice of words, "a subset of our Web API". Nonetheless, my 2 cents are that a good roadmap for this project would be migrating to the official endpoints as they're made available. If the main contributors here decide as so, you @tehkillerbee  included, since I benefit from this package on various projects, in case help is needed, I will be glad to contribute. I will keep an eye here from time to time to see how this develops.

**Comment by Nyabinary** [comment]
![image](https://github.com/tamland/python-tidal/assets/97130632/238130c3-e859-4016-b9c3-29a2d108870c)
Oh boy, lol, I hope this doesn't cause legal troubles for the project.

**Comment by tehkillerbee** [comment]
> I hope this doesn't cause legal troubles for the project.

I think the developers and contributors of python-tidal would prefer to collaborate with Tidal to find a way to achieve both a functioning and open API that does not encourage illicit streaming activities. 

Otherwise, I am sure there are many other open source projects that would love help from some talented programmers such as the (many) contributors to this project.
