### ISSUE TITLE
artist.get_similar() changes artist variable to last similar artist

### ISSUE THREAD

**Issue by Nokse22** [tamland/python-tidal#200]
I don't know what I am doing wrong.
## If I do:

```
print(f"artist is {self.this_artist.name}")

artists = self.this_artist.get_similar()

print(f"after similar() artist is {self.this_artist.name}")
```

I get:

```
artist is The Rolling Stones
after get_similar() artist is Big Brother & The Holding Company
```

the other artist is the last of the similar artists.

## But if I do:

```
print(f"artist is {self.this_artist.name}")

new_artist = self.session.artist(self.this_artist.id)

artists = new_artist.get_similar()

print(f"after get_similar() artist is {self.this_artist.name}")

```

I get what I was expecting

```
artist is The Rolling Stones
after similar() artist is The Rolling Stones
```

I don't this it is supposed to happen.

**Comment by GioF71** [comment]
Hello, I have noticed the same behavior when navigating favorite artists.
If needed, I can also provide some code to reproduce the situation.
Thank you

**Comment by tehkillerbee** [comment]
@Nokse22 @GioF71 thanks for the very detailed description on how to reproduce.

I have not yet had time to look at this issue due to other commitments. Feel free to investigate further, otherwise I'll take a look as soon as RL permits :)

**Comment by GioF71** [comment]
In my case, I got away by keeping track of the id of the original id and reloading when needed. Keeping the variable (I don't remember if it was Artist or Album) was not enough. It did not result to be slower (not too much at least) but of course more code is needed. I will try an see if I can present you a snippet which can reproduce the issue.

**Comment by tehkillerbee** [comment]
@Nokse22 FYI, I can replicate this bug. It looks like this is related to how get_similar() is called using the existing artist as `self`. A subsequent call to `parse_artist` will then end up modifying `self`. A quick solution appears to be passing on a copy of parse_artist when calling get similar. But perhaps a better way is to modify get similar so it is not called in this way.
