### ISSUE TITLE
Scrobbling

### ISSUE THREAD

**Issue by GioF71** [tamland/python-tidal#201]
Hello, is there a way to 'scrobble' the played tracks to Tidal, so that the "Recently played" category can grow with the track we stream using this API?
Thank you!

**Comment by tehkillerbee** [comment]
@GioF71 No this is not currently possible with this API, nor is it possible to get info about the track currently being played using the official clients.

**Comment by GioF71** [comment]
Ok thank you

**Comment by GioF71** [comment]
Just an update (you probably already know), today I tried playing with mConnect Lite and BubbleUpnp with their own method of accessing Tidal, and in both cases there no scrobbling towards Tidal is happening. I guess in any way the scrobbling should be implemented on the renderer if the source is a upnp server.
