### ISSUE TITLE
Last Category in Audio has no title/description

### ISSUE THREAD

**Issue by GioF71** [tamland/python-tidal#204]
Hello, I found that the last category (excluding "Video") has no name and no description, but it contains multiple pagelinks.
How should this category be called? I prepared a snippet and its output so you know what I am talking about:

The snippet of code:

```
home = session.home()
home.categories.extend(session.explore().categories)
#home.categories.extend(session.videos().categories)

# explore last category in audio
last_category = home.categories[len(home.categories) - 1]
print(f"Last category Title [{last_category.title}] Description [{last_category.description}]")

# contents (tldr: PageLinks!)
for last_category_item in last_category.items:
    print(f"Item type is [{type(last_category_item)}]")
    if isinstance(last_category_item, PageLink):
        pl : PageLink = last_category_item
        print(f"  PageLink to api_path: [{pl.api_path}]")
    else:
        print(f"Not a PageLink")
```

The output:

```
Last category Title [] Description []
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/explore_new_music]
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/explore_top_music]
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/rising]
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/cross_genre]
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/clean_content]
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/staff_picks]
Item type is [<class 'tidalapi.page.PageLink'>]
  PageLink to api_path: [pages/podcasts]
```

I cannot find what it matches to in the Tidal Client or the Web Player, but it might be me not being able to find things in the official apps :-)
On my app (actually the Tidal plugin for Upmpdcli) I am naming it "*Untitled*" but it's really ugly, I am scared to call it "From the Staff" or "What's new" because it might one day collide with a future real Category.

Thank you for any feedback!

**Comment by Nokse22** [comment]
Hello. I think it's this part of the explore page:

![IMG_20231004_150923.jpg](https://github.com/tamland/python-tidal/assets/44558032/130aa705-de55-4067-aa9f-44ada011bdd2)
