### ISSUE TITLE
default requests user agent

### ISSUE THREAD

**Issue by scratchmex** [tamland/python-tidal#217]
the library is using the default requests user agent which is something like `python-requests/x.y.z` which could expose that we are using an unofficial api 

is this something you have considered and something to be concerned of?

**Comment by exislow** [comment]
+1 This library should send the respective user agent of the used `client_id`. 

@tamland: What do you think?

**Comment by tehkillerbee** [comment]
@exislow @scratchmex Probably a good idea to change it to match the correct response used by tidal, at least to make sure the unofficial api closely resembles the official one.

Not sure exactly what the correct response should be and currently do not have much time to look into it atm.

**Comment by exislow** [comment]
Let's at least use this one: https://github.com/arnesongit/plugin.audio.tidal2/blob/e9429d601d0c303d775d05a19a66415b57479d87/resources/lib/tidal2/tidalapi/models.py#L39

**Comment by tehkillerbee** [comment]
@exislow Well we could just use that one, but it would be nice to know exactly how to obtain that string and add it as a comment.

**Comment by exislow** [comment]
If the real TIDAL Android app really uses this user agent, this means that they use the system's user agent. A list of different Android user agents can be found here, for instance, https://user-agents.net/browsers/android
