### ISSUE TITLE
[Question] Information about bitrate, file size

### ISSUE THREAD

**Issue by GioF71** [tamland/python-tidal#232]
Hello, I am opening a new issue even if we have another discussion running in my previous, because maybe this can interest others as well.
Is the "bitrate" information available through the library? And file size as well.

Thank you!

**Comment by tehkillerbee** [comment]
Just added it to the stream metadata :)

**Comment by GioF71** [comment]
Amazing, I'll have a look asap

**Comment by tehkillerbee** [comment]
FYI, bitrate is available as part of the stream, as you've discovered. File size is however not directly available and I do not see any easy way to obtain it.

**Comment by GioF71** [comment]
Ok! File size was not really very important anyway, I am ok with bitrate and samplerate of course!
