### ISSUE TITLE
Missing albumReplayGain dictionary entry causes runtime exception

### ISSUE THREAD

**Issue by GioF71** [tamland/python-tidal#240]
Hello, using the current master branch (at commit 979e6cca1a96140b135b5b5ed22b0ff40695a36a), if I change you chosen album_id with 249593867, I get an error with the `albumReplayGain` dictionary entry. Looks like sometimes the information isn't set of course.

Thank you for your attention

**Comment by tehkillerbee** [comment]
@GioF71 Interesting, nice catch. Looks like this issue only occurs for albums where only SONY360 audio mode is available. 

I have made a quickfix but it would be nice to test if this issue also occurs with other audio modes. Have you found any such albums?

**Comment by tehkillerbee** [comment]
The fields are missing for certain albums, eg if they use Sony360 audio mode. But I have changed how these fields are set, so this issue should not occur again.

**Comment by tehkillerbee** [comment]
Fixed in #242
