### ISSUE TITLE
Revert to using enums for relevant classses (Quality etc)

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#243]
Thanks for the new release v0.7.5. I was wondering what, the reason is for the enum cleanups, starting here? https://github.com/tamland/python-tidal/blame/v0.7.5/tidalapi/media.py#L56

Appreciate any information.

**Comment by tehkillerbee** [comment]
Main reason was to avoid needing to call .value to access Enum members, as we usually use their string value anyways.

**Comment by exislow** [comment]
This is is really too bad! Since this project is mainly used as a library by other projects, it makes it really hard to iterate through these "constants". For example: https://github.com/exislow/tidal-dl-ng/blob/e1dfc9ae0b86601e950387882533ab7ea6684f22/tidal_dl_ng/gui.py#L175

I cannot do this anymore to simply populate the GUI with the available quality settings. And I don't see how I can solve this easily not re-assigning all former Enum values.

Would it be possible, if you at least use `dataclasses` (https://docs.python.org/3/library/dataclasses.html)? Actually Enums would be best in my opinion, also because this would be semantically correct.

**Comment by tehkillerbee** [comment]
IMO, it shouldn't be too hard to iterate over the Quality member variables but I see it adds extra work for the libraries that requires this. Besides, the member variables are not immutable, which is probably not the best idea.

Since we do not have `StrEnum` class available unless Python 3.11, an option could be to switch back to the Enum and add 

```
class Quality(str, Enum):

    LOW = 'LOW'
    HIGH = 'HIGH'

    def __str__(self) -> str:
        return self.value
```

Then we avoid calling .value whenever the string value is needed, which is usually the case internally in tidalapi.

**Comment by exislow** [comment]
I actually see no pain in using `.value` on an `Enum`. It's very straight forward and just a few characters more. But you have maybe some other reasons, which really annoys you in this case. Do you plan to raise the supported Python version to 3.11? Otherwise your proposed solution inheriting from `str, Enum` would be the best compromise, I guess.

**Comment by exislow** [comment]
Do you like me to get you an PR on this for the upcoming release?

**Comment by tehkillerbee** [comment]
Sure, that would be great!

**Comment by exislow** [comment]
I got you a PR: https://github.com/tamland/python-tidal/pull/248

**Comment by exislow** [comment]
Thanks for mergin! Have you already a date for the next `tidalapi` release in mind?

**Comment by tehkillerbee** [comment]
@exislow I will try to see if I can get next release ready by the end of the week, at least with the changes from the latest few PRs.
