### ISSUE TITLE
Artist.get_albums_ep_singles() returns empty list

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#245]
Currently I try to get all albums of this artist https://tidal.com/browse/artist/3538682 (Blumentopf).

If I use `Artist.get_albums()` it returns only 4 albums (#Hmlr, 'B-Seiten und Raritäten', 'Gern geschehen', 'Großes Kino'), despite there are actually 11:

<img width="1313" alt="Screenshot 2024-03-22 um 17 21 58" src="https://github.com/tamland/python-tidal/assets/6794066/d1e82788-cc91-439b-a9ad-d5f4dd9d6c21">

If I use `Artist.get_albums_ep_singles()` the result is an empty list. Here I expect to retrieve all albums, EPs and singles. Would this actually even be possible with this filter? Seems like it would leave out the albums, wouldn't it? https://github.com/tamland/python-tidal/blob/6fb5289b698fe40974abf19c0f283b787526ad97/tidalapi/artist.py#L135

What am I doing wrong?

**Comment by tehkillerbee** [comment]
> get_albums_ep_singles()

Yes, this will only return EPs and singles as stated in the function description.

**Comment by exislow** [comment]
Wouldn't it make more sense, to name it like `get_eps_singles()`?

**Comment by tehkillerbee** [comment]
> Wouldn't it make more sense, to name it like `get_eps_singles()`?

I see your point but since it does return album objects, I think this should still be reflected in the name. So I'd say the naming picked makes sense, although slightly confusing. 

I'd be weary with changing the naming of it, in case any external libraries depend on it. 

Still doesn't answer why you don't get all albums. If it is a bug, it must occur with other authors as well.

**Comment by exislow** [comment]
> > Wouldn't it make more sense, to name it like `get_eps_singles()`?
> 
> I see your point but since it does return album objects, I think this should still be reflected in the name. So I'd say the naming picked makes sense, although slightly confusing.

Usually one reflect this with types (typing). To reflect return types in the name declaration is usual, e.g. for C code but not for Python. In the end, you will decide, but my point is simply, that this is very confusing, since other names do not reflect the return type within this library.

> I'd be weary with changing the naming of it, in case any external libraries depend on it.

This would not be the first time, that breaking changes occur. Just kidding :-) Do not get me serious on this.

> Still doesn't answer why you don't get all albums. If it is a bug, it must occur with other authors as well.

I could not observe the same behavior with other artists, so far. Only tested it with 20 artists, yet. But what I can say is, that for some artists some albums are returned as duplicates (up to three times). Is this because of different sound qualities or something? Could you already observe such behavior?

**Comment by tehkillerbee** [comment]
> since other names do not reflect the return type within this library. 

Yes, agreed. Perhaps it would be wise to look through tidalapi and check if there are any other functions with similar confusing names. Let's create a separate issue for these changes. Maybe other developers has opinions on this. 

> Do not get me serious on this. 

Of course, I know what you mean... Of course breaking changes happen but I'd like to create the least inconvenience. 😂

> But what I can say is, that for some artists some albums are returned as duplicates (up to three times). Is this because of different sound qualities or something?

Exactly, these are albums in various audio types (eg. SONY360). I noticed the same thing when browsing albums through mopidy. I'd like to make it easier to filter these albums.

Let's look out for other artists where similar issues occur. I'd like to see if we can find an example where the ep_singles actually return something.

**Comment by exislow** [comment]
I will keep my eyes open and report here, if I can find other examples of this behavior.

I have also created a new issue regarding the naming: https://github.com/tamland/python-tidal/issues/246

**Comment by tehkillerbee** [comment]
Closing this as completed (method is now deprecated)
