### ISSUE TITLE
Remove return types from method names.

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#246]
As discusses in https://github.com/tamland/python-tidal/issues/245

Some methods have ambiguous names, because they use the return type in their name, like https://github.com/tamland/python-tidal/blob/6fb5289b698fe40974abf19c0f283b787526ad97/tidalapi/artist.py#L135

This leads to confusion. One would think, the method would also return albums, but is doesn't. Return types should be declared by typing in general.

Let's collect in this issue all the method names, that have return types in their names and refactor them. To keep backwards compatibility we could leave the "old" name for some weeks printing a deprecation warning, while using it instead of the new methods name.

@tehkillerbee: What do you think?

**Comment by tehkillerbee** [comment]
Agreed, I think this is a good idea.

PRs are of course welcome, otherwise I will take a look at this before next release.

**Comment by exislow** [comment]
I got you a PR on this: https://github.com/tamland/python-tidal/issues/246

I have checked all the files. In my opinion it have been only two methods with explicit return types in their names.
