### ISSUE TITLE
How can I search for an artists?

### ISSUE THREAD

**Issue by dougmellon** [tamland/python-tidal#25]
get_track_url() keeps returning 'None'. Anyone else having this issue?

**Comment by morguldir** [comment]
To search for an artist you just do `search('artist', 'artist_you_want')`

I'm not getting your second issue though, what song is this happening with?

**Comment by prietus** [comment]
hi I cannot get track urls either.
I get just nothing, no error though.

**Comment by morguldir** [comment]
Closing this since the body of your post has been solved in f21bd307e28973846ee0b9d14d15bca1d37559f3
