### ISSUE TITLE
Bug: audio_modes is a list but is linted as Optional[str]

### ISSUE THREAD

**Issue by GioF71** [tamland/python-tidal#261]
Apologies if this somehow duplicates my previous issue, but I see from `album.py` that the attribute `audio_modes` should be `Optional[str]`
However, testing the type from code, I see it is actually a `list`, which then contains typically one `str`.
Thank you for any feedback!

**Comment by tehkillerbee** [comment]
Yes, this looks like a bug.

**Comment by GioF71** [comment]
Thank you very much!

**Comment by GioF71** [comment]
sorry, the bug is in the linting or in the implementation that returns the list?

**Comment by tehkillerbee** [comment]
Yes, looks like the linting is incorrect, as more than one audio type can be returned in the list.
