### ISSUE TITLE
Playlists created with `python-tidal` are not visible with `python-tidal`

### ISSUE THREAD

**Issue by Nokse22** [tamland/python-tidal#264]
I have created a playlist using:

```
session.user.create_playlist(playlist_title, playlist_description)
```

but are not visible using 
```
session.user.favorites.playlists()
```
even when restarting my app all the playlist created using `python-tidal` remain invisible.

### Create
I have looked at the way the website is making a new playlist and it is using:

```
PUT https://listen.tidal.com/v2/my-collection/playlists/folders/create-playlist?description=&folderId=root&isPublic=false&name=PLAYLIST_NAME&countryCode=IT&locale=en_US&deviceType=BROWSER
```

but `python-tidal` is using [this](https://github.com/tamland/python-tidal/blob/288fc1ea53d6ca0a23424795ecae3a09b0ec43a3/tidalapi/user.py#L167-L173):

```
    json = self.request.request(
            "POST", "users/%s/playlists" % self.id, data=data
        ).json()
```

### Get

The website uses these to get the playlists:

```
/v1/users/ID/favorites/ids
/v2/my-collection/playlists/folders
```
The first gets all the favorites, but in the playlists the one made with `python-tidal` is missing, with the second one it's not.

The `python-tidal` uses the first method, I think.

**Comment by tehkillerbee** [comment]
I double checked this myself, as I assumed the API was broken. It turns out the playlists are indeed created, but you cannot find them using the method that you called, simply because `session.user.favorites.playlists()` does not include user created playlists.

See the difference here:
```python
playlists = session.user.playlists()
print("User playlists")
for playlists in playlists:
    print("{}: '{}' by '{}'".format(playlists.id, playlists.name, playlists.created))

playlists_favs = session.user.favorites.playlists()
print("User favourite playlists")
for playlists in playlists_favs:
    print("{}: '{}' by '{}'".format(playlists.id, playlists.name, playlists.created))

playlists_and_favs = session.user.playlist_and_favorite_playlists()
print("User playlists and favourite playlists")
for playlists in playlists_and_favs:
    print("{}: '{}' by '{}'".format(playlists.id, playlists.name, playlists.created))
```

`session.user.playlists()` includes the playlists but `session.user.favorites.playlists()` does not.

**Comment by Nokse22** [comment]
Thank you! It was my first thought too.
