### ISSUE TITLE
Automating Login for Cloud Functions

### ISSUE THREAD

**Issue by dennis-dsi** [tamland/python-tidal#269]
Hi, first of all thank you so much for maintaining this project! The API is amazing!

I wanted to deploy my project in the cloud to avoid manually running the scripts to track my music.
Everything worked great until I just noticed, that the key expired and I had to manually go in and update it.

For some reason, all login methods require human interventation, like loggin into the browser or pasting the URL in the console.
I just tried the simple `login(username, password)` method, but I got `401 Client Error: Unauthorized for url: https://api.tidal.com/v1/login/username` this error. Even if I don't use the refresh token, the session has an expiary date.

What would you suggest is the best way to deploy this in the cloud without having to manually update the access token every week?

**Comment by tehkillerbee** [comment]
It's true, the first login requires human intervention. But all following re authentication  should be completely automatic and is handled if/when the token has expired.

Saving the token to a file and reloading this token again should be all that is needed. Are you not saving / reloading the token from file?

**Comment by dennis-dsi** [comment]
Sorry, I don't know to which function you are refering to :)

I am assuming that the `login(username, password)` not with the Tidal API comaptable is, because I receive the `requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/login/username` error.

So I would manually run `session.login_oauth_simple()` one time and get the `access_token` and then just run `load_oauth_session` without any adjustments? But this function does not update the token automatically and will return False after a week or so.

The last thing is the `login_session_file`, but I don't want to save my creds in the code path, because this would not be secure, so I am unsure as to how to proceed. :/

**Comment by dennis-dsi** [comment]
Okay thank you, this help me! 

I am using GCP and for good practices I don't want to save the token in the same file in case I share the code without removing this. But I will just use the `login_session_file` that automatically refreshes.

**Comment by tehkillerbee** [comment]
Good to hear. Yes, using the login_session_file should work fine in this case when deployed to google cloud, although it is not something I have tested myself :)
