### ISSUE TITLE
Tracks with only one element in their manifest's `SegmentTimeline` cause a crash when creating `DashInfo`

### ISSUE THREAD

**Issue by romner-set** [tamland/python-tidal#273]
Cause of https://github.com/exislow/tidal-dl-ng/issues/156 & https://github.com/exislow/tidal-dl-ng/issues/160.

Tracks like [281047832](https://tidal.com/browse/track/281047832) and [51332556](https://tidal.com/browse/track/51332556) have a `SegmentTimeline` in their manifest that looks like this:
```xml
<SegmentTimeline>
  <S d="176128" r="72"></S>
</SegmentTimeline>
```
Instead of the usual:
```xml
<SegmentTimeline>
  <S d="176128" r="84"></S>
  <S d="163135"></S>
</SegmentTimeline>
```
Which causes an out-of-bounds crash here, specifically the `.Ss[1]` bit:
https://github.com/tamland/python-tidal/blob/288fc1ea53d6ca0a23424795ecae3a09b0ec43a3/tidalapi/media.py#L718-L726

Changing it to `.Ss[-1]` should fix the issue.

**Comment by tehkillerbee** [comment]
Thanks for the detailed explanation, much appreciated. Will try to get this fixed in the next release.
