### ISSUE TITLE
Feature request: login_session_file method with optional print function as argument

### ISSUE THREAD

**Issue by tehkillerbee** [tamland/python-tidal#282]
To make it easier to integrate python authentication with external python modules, it should be possible to provide an optional print function as argument to the method login_session_file

_Originally posted by @GioF71 in https://github.com/tamland/python-tidal/issues/277#issuecomment-2344351002_

**Comment by GioF71** [comment]
Hello, I will gladly implement this. Should I branch from master or from feature/v0.7.7-prep3? Thank you

**Comment by tehkillerbee** [comment]
Fixed in #283
