### ISSUE TITLE
Detecting unavailable tracks

### ISSUE THREAD

**Issue by dennisklad** [tamland/python-tidal#285]
Hi, thanks so much for this API!! 

I had a question: Is there a way to detect the unavailable tracks? This has been annoying me and wanted to check if there is a way to replace them with the API. 

Thanks in advance.

![image](https://github.com/user-attachments/assets/c4f8773a-41fd-4a0b-a520-431f7e2811cd)

**Comment by dennisklad** [comment]
The track has this function, but I am not sure if this is what I want:
https://github.com/tamland/python-tidal/blob/c0a6aef57e7eac8232cf491b0316f6c8d0f5da87/tidalapi/media.py#L419C1-L419C105

Furthermore each Media object has the attribute `available`, but this is not inhereted by the Track class:
https://github.com/tamland/python-tidal/blob/c0a6aef57e7eac8232cf491b0316f6c8d0f5da87/tidalapi/media.py#L192C1-L192C27

Any help is appreciated :)

**Comment by dennisklad** [comment]
Sorry, just tested it and there is indeed the boolean `available` that is inhereted from Media.
https://github.com/tamland/python-tidal/blob/c0a6aef57e7eac8232cf491b0316f6c8d0f5da87/tidalapi/media.py#L192C1-L192C27

**Comment by tehkillerbee** [comment]
Sure, as you have now found out! you can use the .available attribute.

Also, albums, tracks etc that are not available will throw an exception when fetched directly:

```
from pathlib import Path

import tidalapi
from tidalapi import exceptions

session_file1 = Path("tidal-session-oauth.json")

session = tidalapi.Session()
# Load session from file; create a new OAuth session if necessary
session.login_session_file(session_file1)

tracks = ["381616195", "5587976"]  # Track #2 is not available
# Check if tGet user tracks and check if track is available
for track_id in tracks:
    try:
        track = session.track(track_id=track_id)
    except exceptions.ObjectNotFound:
        print(f"Track {track_id} not available")
```

**Comment by dennisklad** [comment]
Perfect! Also, I noticed that it is not possible to directly add the track again to the favorites as it has a new ID and it throws a 404. 

From this [convo ](https://github.com/tamland/python-tidal/issues/96) I see that it is also not possible with the isrc, right? 
I would have to do a full text search on the track and add it this way?

**Comment by dennisklad** [comment]
For anyone that is interested this is my code:

```
