### ISSUE TITLE
cannot get track url

### ISSUE THREAD

**Issue by prietus** [tamland/python-tidal#29]
`git clone https://github.com/tamland/python-tidal.git
cd python-tidal
python setup.py install --user`

`res = session.search('artist', 'queen')
band = res.artists[0].name
artist_id = res.artists[0].id
albums = session.get_artist_albums(artist_id)
for a in albums:
    album = session.get_album(a.id)
    album_id = a.id
    album_name = a.name
    tracks = session.get_album_tracks(album_id)
    for t in tracks:
        track = session.get_track(t.id)
        session.get_track_url(track.id) != None`
still no output

**Comment by morguldir** [comment]
session.get_track_url() doesn't print anything, it only returns the url so you can use it. I'm not completely sure what your code is trying to do, but you would have to write `print(session.get_track_url(track.id))` if you wanted it to print the url.

**Comment by prietus** [comment]
my bad, youre right. sorry for the noise
