### ISSUE TITLE
version in __init__.py still 0.7.7

### ISSUE THREAD

**Issue by jozefKruszynski** [tamland/python-tidal#294]
After the decision to go with 0.8.0 as the new version, it seems that __init__.py was missed

https://github.com/tamland/python-tidal/blob/da172376705ad43ad5142025dca71ba9919e67f7/tidalapi/__init__.py#L22C1-L22C22

**Comment by tehkillerbee** [comment]
Thanks, I've fixed it on the master.

**Comment by jozefKruszynski** [comment]
Not sure why I linked to the original commit branch and not master 😄
