### ISSUE TITLE
HIRES naming inconsistency

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#296]
As discussed in this issue #255 TIDAL itself uses `HI_RES` but `tidalapi` still uses `HIRES`, despite the intention to change it to `HI_RES` (see https://github.com/tamland/python-tidal/issues/255#issuecomment-2068184005).

Was #255 closed on purpose without without renaming every occurrence of `HIRES` to `HI_RES`? Just asking to make sure, if I missed something.

References:
* https://github.com/tamland/python-tidal/blob/910a7b4b84b313259d3388b19e44818b0c4a414b/tidalapi/media.py#L89
* https://github.com/tamland/python-tidal/blob/910a7b4b84b313259d3388b19e44818b0c4a414b/tidalapi/media.py#L445

**Comment by tehkillerbee** [comment]
Yes, the intention was to change the naming so it corresponds to the naming used by tidal. But perhaps I overlooked some of them as I was mainly concerned about making sure the names followed python naming conventions.

**Comment by exislow** [comment]
Thanks for clarification. Can properly align the names? May I get you a PR?

**Comment by tehkillerbee** [comment]
Sure, PR is very welcome!

**Comment by exislow** [comment]
Got you a PR.
