### ISSUE TITLE
MQA is no more. Remove legacy code.

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#297]
MQA is no longer offered by TIDAL -- yay! Should we remove the MQA legacy (`HI_RES`) in `tidalapi`?

References:
* https://github.com/tamland/python-tidal/blob/910a7b4b84b313259d3388b19e44818b0c4a414b/tidalapi/media.py#L483
* https://github.com/tamland/python-tidal/blob/910a7b4b84b313259d3388b19e44818b0c4a414b/tidalapi/media.py#L61

**Comment by exislow** [comment]
@tehkillerbee: What is your opinion on that? I could get you a PR for this, too.

**Comment by tehkillerbee** [comment]
Yes, I think we can safely remove it. But IIRC, there are some tests that should be disabled/removed too. 

PR is also much appreciated :+1:

**Comment by exislow** [comment]
Got you a PR.
