### ISSUE TITLE
Wrong return of Track.get_urls()

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#298]
So this method https://github.com/tamland/python-tidal/blob/910a7b4b84b313259d3388b19e44818b0c4a414b/tidalapi/media.py#L594-L598

Clearly states, that it returns `[str]`.

But within the else statement we find this code piece `return self.urls[0]` which only returns a `str`.

I propose, to match the name `get_urls()` and the return type `[str]`, that the method should look like this:

```python
    def get_urls(self) -> [str]:
        return self.urls
```

**Comment by tehkillerbee** [comment]
Since we can still return both, I suggest `.. -> Union[str, [str]]` instead

**Comment by exislow** [comment]
I would not vote for this, since the name is suggesting, that URLs (plural) are returned. Thus, everybody would expect a list. 

Plus it makes code software easier. Otherwise I need to check every time if a list is returned or not in my own code base, which is super annoying.

**Comment by tehkillerbee** [comment]
Still, the typings should reflect the actual type returned.

A better alternative would be to stick to [str] and then return [self.urls[0]]

**Comment by exislow** [comment]
Thanks. I got you a PR.
