### ISSUE TITLE
Return raw values in `_login_with_link` to able to process them further.

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#302]
We have currently no method, which allows to handle an OAuth (device login) by another applications thread pool. 

I suggest to use `login_oauth` to return `LinkLogin` and the `future` instance. `_login_with_link` will only return the JSON values and can be used to bootstrap the login in 3rd party apps code and their own thread pools. 

I will get you a PR.

**Comment by exislow** [comment]
There you go: https://github.com/tamland/python-tidal/pull/303

Let me know what you think.

**Comment by tehkillerbee** [comment]
Fixed in #303
