### ISSUE TITLE
Retrieve album by Barcode ID

### ISSUE THREAD

**Issue by c0ball** [tamland/python-tidal#308]
As the library since version 0.8.0 allows the retrieval of albums by barcode ID (UPC), I wanted to ask if someone can show me an example of how exactly the Python interaction must look like if I have saved the ID e.g. in a string.

**Comment by tehkillerbee** [comment]
Sure, take a look at the tests here:
https://github.com/tamland/python-tidal/blob/master/tests/test_session.py#L158-L179

**Comment by c0ball** [comment]
Thanks a lot. 🙏

**Comment by tehkillerbee** [comment]
This is simply a wrapper around the tidal OpenAPI. So the way this function is used is to filter a list of albums, using the UPC:
https://developer.tidal.com/apiref?spec=catalogue-v2&at=THIRD_PARTY&ref=get-albums-v2

**Comment by c0ball** [comment]
Ah, I understand
