### ISSUE TITLE
File extension determination algorithm update.

### ISSUE THREAD

**Issue by exislow** [tamland/python-tidal#309]
There have been some changes on TIDALs side. Hence, I need to update the file extension determination algorithm. TIDAL now streams files with ".m4a" instead of "mp4" as extension. I will get you an PR.

**Comment by exislow** [comment]
@tehkillerbee would be great, if you could have a look at it. Maybe worth a hot fix release.

**Comment by exislow** [comment]
By any chance: Do already have a date for the next release?

**Comment by exislow** [comment]
@tamland: Forgot to mention you in my question above.

**Comment by tehkillerbee** [comment]
Not sure if you meant to tag me or tamland. Anyways, I will most likely update the release during the holidays. 

Otherwise, if you prefer "bleeding edge", you can always point to the latest master it in your dependency, similar to this example:
```
[tool.poetry.dependencies]
python = "^3.6"
ansible = { git = "https://github.com/ansible/ansible.git", branch = "devel" }
# or
ansible = { git = "https://github.com/ansible/ansible.git", tag = "v2.6.6" }
# or
ansible = { git = "https://github.com/ansible/ansible.git", rev = "e5664c4" }
```

**Comment by exislow** [comment]
@tehkillerbee have just seen, that only you are mentioned in the README as the only active maintainer, sorry for that.

PyPi does not accept hotlinks to git repositories, if I try to publish a new release. But I can wait a few days. Do not worry and thanks a lot!

**Comment by exislow** [comment]
Which holidays did you exactly mean btw? :)

**Comment by tehkillerbee** [comment]
@exislow I was working on it, right as you wrote. Updated to latest release now. :)
