### ISSUE TITLE
List of functions to move over to 0.7.0

### ISSUE THREAD

**Issue by morguldir** [tamland/python-tidal#31]
We want to make sure we move over every function to the new format

- [x] get_album(album_id)
  - [x] tests

- [x] get_album_items(album_id)
  - [x] tests

- [x] get_album_tracks(album_id)
  - [x] tests

The way we did this function was just removing the tracks from the playlist, is is probably not that useful.
> ~get_album_videos(album_id)~
     ~tests~

- [x] get_artist(artist_id)
  - [x] tests

- [x] get_artist_albums(artist_id)
  - [x] tests

- [x] get_artist_albums_ep_singles(artist_id)
  - [x] tests

- [x] get_artist_albums_other(artist_id)
  - [x] tests

- [x] get_artist_bio(artist_id)
  - [x] tests

- [x] get_artist_radio(artist_id)
  - [x] tests

- [x] get_artist_similar(artist_id)
  - [x] tests

- [x] get_artist_top_tracks(artist_id)
  - [x] tests

- [x] get_artist_videos(artist_id)
  - [x] tests

- [x] get_genre_items(genre_id, content_type)
  - [x] tests

- [x] get_genres()
  - [x] tests

This was just get_track_url
>~get_media_url(track_id)~
  ~tests~

These have been deprecated by TIDAL and will be added later
>~get_mood_playlists(mood_id)~
  ~ tests~

>~get_moods()~
  ~tests~

>~get_featured()~
  ~tests~

>~get_featured_items(content_type, group)~
  ~tests~

- [x] get_playlist(playlist_id)
  - [x] tests

- [x] get_playlist_items(playlist_id)
  - [x] tests

- [x] get_playlist_tracks(playlist_id)
  - [x] tests

No actual endpoint
>~get_playlist_videos(playlist_id)~
  ~tests~

- [x] get_track(track_id)
  - [x] tests

- [x] get_track_radio(track_id)
  - [x] tests

- [x] get_track_url(track_id)
  - [x] tests

- [x] get_user(user_id)
  - [x] tests

- [x] get_user_playlists(user_id)
  - [x] tests

- [x] get_video(video_id)
  - [x] tests

- [x] get_video_url(video_id)
  - [x] tests

- [x] load_session(session_id, country_code=None, user_id=None)
  - [x] tests

- [x] login(username, password)
  - [x] tests

- [x] request(method, path, params=None, data=None)
  - [x] tests

- [x] search(field, value, limit=50)
  - [x] tests

# class tidalapi.User(session, id)

- [x] playlists()
  - [x] tests

# class tidalapi.Favorites(session, user_id)

- [x] add_album(album_id)
  - [x] tests

- [x] add_artist(artist_id)
  - [x] tests

- [x] add_track(track_id)
  - [x] tests

- [x] add_video(video_id)
  - [x] tests

- [x] albums()
  - [x] tests

- [x] artists()
  - [x] tests

- [x] playlists()
  - [x] tests

- [x] videos()
  - [x] tests

- [x] remove_album(album_id)
  - [x] tests

- [x] remove_artist(artist_id)
  - [x] tests

- [x] remove_track(track_id)
  - [x] tests

- [x] tracks()
  - [x] tests

**Comment by JuniorJPDJ** [comment]
What's blocking 0.7.x from being default version now?

**Comment by morguldir** [comment]
The /pages endpoint, this would include the `Explore`, `Videos`, and `Home` pages from the various TIDAL interfaces, as well as the links on those pages. This would include #62 as well, i have it mostly finished locally. Some version of #68, i also want to make the docstrings more complete and include some more detailed usage examples. I want to wait with pushing 0.7.x to master until I am ready to release 0.7.0 to PyPI, which should be after these things are finished, unless something else comes up. I still recommend using 0.7.x before this though.

**Comment by BuddhaOhneHals** [comment]
I'd be happy to see the support for Mixes as requested in #62. But before I start to implement it by myself I wanted to ask, if you could share your current implementation in any way (a fork, a branch, ...).

**Comment by onestix** [comment]
Hi @morguldir, bumping this one here- can we get a release of 0.7.x to PyPI yet?

**Comment by morguldir** [comment]
I won't have much time until next month, but

> I'd be happy to see the support for Mixes as requested in #62. But before I start to implement it by myself I wanted to ask, if you could share your current implementation in any way (a fork, a branch, ...).

I guess my comment was kinda unclear, it works with the /pages endpoints, but without mixes, although mixes don't really require any special handling, it should be pretty quick to add, and not fully sure if my code is ready for sharing right now, and don't really have time to check, sorry about that.

> Hi @morguldir, bumping this one here- can we get a release of 0.7.x to PyPI yet?

I can probably do a pre-release next month, but pip let's you put git links inside the requirements.txt file, so it's not strictly necessary, but i will likely do it anyway.

**Comment by onestix** [comment]
Thank you!

**Comment by onestix** [comment]
hey @morguldir, any luck with getting release of 0.7.x to PyPI yet? Cheers

**Comment by bjesus** [comment]
Hey, I see that `get_track_radio(track_id)` is marked as ✅, but I can't figure out where it is now, and also I can't seem to see any test for it under https://github.com/tamland/python-tidal/blob/master/tests/test_media.py .... am I missing something? Is it possible to get the track radio somehow?
