### ISSUE TITLE
Can't login anymore?

### ISSUE THREAD

**Issue by bjesus** [tamland/python-tidal#32]
I wonder if it's just me, but I can't login using python-tidal anymore. I'm getting this error:
```
Traceback (most recent call last):
  File "sync.py", line 6, in <module>
   mysession.login('*******', '*******)
  File "/home/*******/env/lib/python3.8/site-packages/tidalapi/__init__.py", line 77, in login
    r.raise_for_status()
  File "/home/*******/env/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=*******
```

Logging in through the browser at listen.tidal.com with the exact same credentials works normally. What happened?

**Comment by morguldir** [comment]
Looks like you are using an old version due to the r.raise_for_status being on line 77. It seems that they killed of the api key used in that version,

Please reopen if you still have issues after updating.

**Comment by bjesus** [comment]
Apologies, you're of course right. Upgrading from 0.6.1 to 0.6.4 solved it.
