### ISSUE TITLE
Will there be any changes in syntax with the 0.7 release?

### ISSUE THREAD

**Issue by swanux** [tamland/python-tidal#33]
I'm currently writing a GUI Tidal program for Linux with Python and GTK3 using your API, and I'm wondering if there will be any significant changes in the usage of the API or not. If there are going to be major changes, then I'd rather wait for the next release, but otherwise I'd like to begin coding.

**Comment by morguldir** [comment]
Yes, the current syntax does not allow for multiple files and the models aren't very robust . What I'm hoping to do is to not break current programs, but the old syntax will be deprecated and i won't be adding more features to it.

I would recommend waiting with the tidalapi parts of your program at least.

**Comment by swanux** [comment]
Ok, thank you, I'll do that then. I know it's hard to say an exact date, but can you tell me an evaluation about when the next release will arrive?

**Comment by morguldir** [comment]
Hard to know how much time i will have to work on it, but probably at some point in may.

**Comment by swanux** [comment]
Good work then! And thanks for the information.

**Comment by swanux** [comment]
How is the development going?
