### ISSUE TITLE
Update to latest token

### ISSUE THREAD

**Issue by tehkillerbee** [tamland/python-tidal#36]
I have noticed that other (illegal?) tidal tools has updated their token although I am not exactly sure where this token has been obtained. After updating my python-tidal installation to this token, the plugin works again: hZ9wuySZCmpLLiui

**Comment by morguldir** [comment]
I chose to find another token as that one is an apple token and uses ALAC over FLAC for lossless streams, and FLAC is more widespread. That token also doesn't support numberOfVideos in playlists, which i am planning to add in 0.7.0.

**Comment by tehkillerbee** [comment]
Ah! That explains why the lossless streams switched to ALAC all of a sudden when I used the above token as a quick fix. I did not know the token works like that.

How did you obtain this other token? From the Tidal windows application?

**Comment by JuniorJPDJ** [comment]
As far as I know that's not problem with token. Tidal changed something. My friends was able to download flac using token which on default pushed ALAC now.

**Comment by morguldir** [comment]
@tehkillerbee That one is from an older android version of TIDAL, which supported my old device. Most of the current TIDAL programs use oauth currently, which requires a different way of logging in.

@JuniorJPDJ Tidal has had different tokens for a while now, some programs loop through different keys until they are able to log in, i don't think there are that many tokens that support unencrypted FLAC.
