### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by hYpac0w** [tamland/python-tidal#37]
Hello,

I am unable to sign into my Tidal account following the example usage.
This is my code:

```python
import tidalapi

session = tidalapi.Session()
user = 'myemail'
pw = 'mypw'

session.login(user, pw)
```

First I got the following error:
```python
{"status":401,"subStatus":6004,"userMessage":"Invalid token"}
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    session.login(user, pw)
  File "C:\Users\alper\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tidalapi\__init__.py", line 87, in login
    request.raise_for_status()
  File "C:\Users\alper\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=pl4Vc0hemlAXD0mN
```

After looking up my personal API token and editing the `__init__` file I get this error:
```python
{"status":401,"subStatus":3009,"userMessage":null}
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    session.login(user, pw)
  File "C:\Users\alper\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tidalapi\__init__.py", line 87, in login
    request.raise_for_status()
  File "C:\Users\alper\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Hope someone can help me out :)

**Comment by swanux** [comment]
Hello,

Well, this won't be helpful, just a confirmation. 
After I've seen your issue I've checked if I can login or not, and it turned out I can't. It worked fine until the previous day. I guess it's the same that happened 11 days ago.
You can refer to this issue if you missed it: #36 
Hopefully @tamland can fix it this time as well.

**Comment by morguldir** [comment]
Thanks for letting me know.

I used another token and decided to obfuscate it, doesn't do that much but it does help slightly. TIDAL was probably already planning on disabling all the android tokens, but it happened pretty closely to me saying i was using android tokens, and it's kind of weird that they seemingly disabled all of the android tokens using the old logins.

**Comment by swanux** [comment]
Great!
What do you mean? How does obfuscating it help?

**Comment by morguldir** [comment]
Just that if TIDAL is looking at this repository they won't be able to instantly see what token is being used and revoke it.

**Comment by swanux** [comment]
Oh okay, I've got it. I've done something similar with github access tokens.
Good work on the 0.7 release, I'm eagerly waiting for it!
