### ISSUE TITLE
Get Playlist Creator Always None

### ISSUE THREAD

**Issue by KengoWada** [tamland/python-tidal#40]
When I try getting the playlist creator it always returns None. Is there something I'm doing wrong or is this normal behaviour?

**Comment by morguldir** [comment]
The parsing has not been implemented yet, the attribute probably should have been commented out as well.

https://github.com/tamland/python-tidal/blob/251ed480cb8ba33eeec16436593e409c49540122/tidalapi/__init__.py#L327-L337

**Comment by nam20485** [comment]
Just a quick question- does this API contain support for creating new playlists and adding tracks to them? That is what I am looking for.

**Comment by KengoWada** [comment]
Yes, you can create playlists and add tracks to it.
Check this out: https://github.com/tamland/python-tidal/issues/23#issuecomment-603221265
