### ISSUE TITLE
Login method no more works

### ISSUE THREAD

**Issue by trumpeta** [tamland/python-tidal#41]
Using tidalapi 0.6.3:

> import tidalapi
> session = tidalapi.Session()
> session.login('trumpeta@gmail.com', '***************')

produces HTTP error 401:

```
{"status":401,"subStatus":6004,"userMessage":"Invalid token"}
Traceback (most recent call last):
  File "<console>", line 0, in <module>
  File "D:\develop\Python\lib\site-packages\tidalapi\__init__.py", line 83, in login
    request.raise_for_status()
  File "D:\develop\Python\lib\site-packages\requests\models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOOmYk3zShYrNP
```

I suppose the deprecated login endpoint https://api.tidalhifi.com/v1/login/username is no more handled.
(If I try to login using same credentials through Tidal web, the sign in is completed.

**Comment by Mehavoid** [comment]
API token is deprecated. Use 0.6.6 version instead.

**Comment by trumpeta** [comment]
You're right, I was using old version. the new token is for amarra. Did you realize these device tokens are being revoked and this login method stops to work soon?
Would you consider to change the login method to Oauth2?

**Comment by morguldir** [comment]
The v0.6.8 release now supports logging in with OAuth.

**Comment by sorenwacker** [comment]
I only get this output: 
```

(<tidalapi.LinkLogin at 0x7f6e6c7d44c0>,
 <Future at 0x7f6e6c7d48e0 state=running>)
```
