### ISSUE TITLE
HELP - Search

### ISSUE THREAD

**Issue by TheProgrammingM** [tamland/python-tidal#44]
Hey, i wanted to ask, how to parse the <tidalapi.models.SearchResult object at 0x...>.
I haven't found any documentation about it :(
I just don't know what to do after the session.search...

Here is a part of my code:

> query = "python"
> session = tidalapi.Session()
> session.login('username', 'password')
> tracks = session.search("track", query, 1)
> print(tracks)

Thanks for helping me out (:

**Comment by TheProgrammingM** [comment]
I read the code, and after 4 hours I'm finally understanding it (:
If someone likes to know how it works, feel free to open this "issue" again.
Have a nice day!

**Comment by josopu** [comment]
Hey! I would like to know how it works. Hope you can give me a hint :smile:

**Comment by Maerchensarg** [comment]
Please let the people know how it works.

**Comment by hackmybeer** [comment]
Hey,
I don‘t know if this helps you, but the following function searches for songs based on the query parameter, filters duplicates and sorts them after their popularity. In general to access the songs in the object you need to use queryObj**.tracks**.

Example:
![code-img](https://i.imgur.com/XGXAGZJ_d.webp?maxwidth=1520&fidelity=grand)
