### ISSUE TITLE
Album art not setting / not downloading properly

### ISSUE THREAD

**Issue by SVR666** [tamland/python-tidal#48]
**code :-** 

```
def download(url, file_name):
	with open(file_name, "wb") as file:
		response = get(url) 											
		file.write(response.content)

track = session._map_request('tracks/'+str(track_id), params={'limit': 100}, ret='tracks')
download(track.album.image, 'music/'+name+'.png')
```

**anything wrong in this code?**

**Comment by DerNuntius** [comment]
https://github.com/tamland/python-tidal/issues/38

**Comment by tehkillerbee** [comment]
This issue appears to be fixed in this fork by [ktnrg45](https://github.com/ktnrg45/python-tidal/commit/e231053a1ec7016d941986313b4079955bedc885). Is there a reason it has not been merged into python-tidal?

**Comment by SVR666** [comment]
> This issue appears to be fixed in this fork by [ktnrg45](https://github.com/ktnrg45/python-tidal/commit/e231053a1ec7016d941986313b4079955bedc885). Is there a reason it has not been merged into python-tidal?



> #38

Thanks
