### ISSUE TITLE
any way to get lyrics and genre ?

### ISSUE THREAD

**Issue by SVR666** [tamland/python-tidal#52]
is there any way to get lyrics and genre of a track?

**Comment by swanux** [comment]
Regarding the first part of the question, Tidal currently doesn't support Spotify / Shazam like lyrics option. (some users report though that it's available in Poland [here](https://www.reddit.com/r/TIdaL/comments/gtbogx/tidal_lyrics_available_on_mobile_a_followup_to_my/))

**Comment by morguldir** [comment]
This is available with e.g. `session.track(track_id).lyrics()` in the 0.7.x branch now.
