### ISSUE TITLE
New login method recommended

### ISSUE THREAD

**Issue by swanux** [tamland/python-tidal#54]
Because static tokens won't work forever (thanks for being "open", Tidal...) it should be taken into consideration to migrate one of the supported new login methods. Maybe the best would be somehow through browser based oauth2 (if it's possible).

**Comment by swanux** [comment]
You may take a look at [this](https://github.com/Fokka-Engineering/libopenTIDAL) implementation, as it supports OAuth.

**Comment by JuniorJPDJ** [comment]
There's some writeup: https://github.com/Fokka-Engineering/TIDAL/wiki/Authentication

**Comment by JuniorJPDJ** [comment]
https://github.com/quodrum-glas/python-tidal
This fork seems to support oAuth
