### ISSUE TITLE
add_track returns 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by bkr32** [tamland/python-tidal#58]
when attemtping to use add_track to favorites when favorites already has 49 items returns the following error

```
Traceback (most recent call last):
  File ".\tidal_add_tracks.py", line 16, in <module>
    TidalUser2.add_track(track.id)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tidalapi\__init__.py", line 392, in add_track
    return self._session.request('POST', self._base_url + '/tracks', data={'trackId': track_id}).ok
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tidalapi\__init__.py", line 124, in request
    request.raise_for_status()
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidalhifi.com/v1/users/UserID/favorites/tracks?sessionId=SESSIONID&countryCode=&limit=10000
```

**Comment by morguldir** [comment]
I can't reproduce the error with 49 items

The error is probably indicating the the track id doesn't exist, what is the track id you are trying to add?

**Comment by bkr32** [comment]
@morguldir some background context, I created a new account and consequently used the API to migrate my data (other services just ain't that good).
As such I created a script that fetches the entire favorite list of the source account (so far so good)
And then used add_track on destination account to add them as favorites.
Now after 49 songs and it throws the above error, after which whenever I try to add any song via the API I get the same error, 
At first I thought it was region blocked but noticed it did in fact add region blocked songs but they were unplayable.

Here's a example of one such song (no region blocked)
http://tidal.com/browse/track/126144034

**Comment by morguldir** [comment]
I suspect that the last song you added has some sort of region lock, if you remove another track from your favorites does the error still come up? That would show if the error is related to the amount of items.

If it's just the last track you added that's causing issues can you post the track id of that?

**Comment by bkr32** [comment]
@morguldir I thought so as well, that's why I tried individual tracks, which is basically add_track with a specified track ID, tried the above posted and others and still the same result (see read add tracks from above repo).

Funny part is I mistakenly added a large number of tracks from various albums and artists going upwards of 1k with no issue.

Lastly I dumped the track ID's from the source account onto a track ID list and used that as a source to debug but still the same

**Comment by bjesus** [comment]
I had my own function to add tracks to a playlist:
```python
new.request('POST', 'playlists/%s/tracks' %
  new_id, data=data, headers=headers)
```

Recently it started failing with the same error:
```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    new.request('POST', 'playlists/%s/tracks' %
  File "XXX/python3.8/site-packages/tidalapi/__init__.py", line 128, in request
    request.raise_for_status()
  File "XXX/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidalhifi.com/v1/playlists/a9229a3d-5806-4e58-b66f-71847f6f2464/tracks?sessionId=XXX&countryCode=SE&limit=999
```

It was working perfectly so I suspect something changed on their end.

**Comment by morguldir** [comment]
Just added a commit to the 0.6.x branch that will output more info, can both of you see what it outputs with that?

@bjesus does this happen with arbitrary track ids for you as well?

**Comment by bkr32** [comment]
@morguldir i've come out with 2 different error messages
for the source to dist account favorites transfer it gives

```
{"status":404,"subStatus":2001,"userMessage":"Album not found"}
Traceback (most recent call last):
  File ".\tidal_add_tracks.py", line 16, in <module>
    TidalUser2.add_track(track.id)
  File "\AppData\Local\Programs\Python\Python37\lib\site-packages\tidalapi\__init__.py", line 396, in add_track
    return self._session.request('POST', self._base_url + '/tracks', data={'trackId': track_id}).ok
  File "\AppData\Local\Programs\Python\Python37\lib\site-packages\tidalapi\__init__.py", line 126, in request
    request.raise_for_status()
  File "\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidalhifi.com/v1/users/X/favorites/tracks?sessionId=&countryCode=&limit=999
```

and for the read from file and add


```
{"status":500,"subStatus":999,"userMessage":"Ooops, an unexpected error occurred. We'll try to fix this asap!"}
Traceback (most recent call last):
  File ".\tidal_read_add_tracks.py", line 14, in <module>
    TidalUser.add_track(artist)
  File "\32\AppData\Local\Programs\Python\Python37\lib\site-packages\tidalapi\__init__.py", line 396, in add_track
    return self._session.request('POST', self._base_url + '/tracks', data={'trackId': track_id}).ok
  File "\32\AppData\Local\Programs\Python\Python37\lib\site-packages\tidalapi\__init__.py", line 126, in request
    request.raise_for_status()
  File "\32\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.tidalhifi.com/v1/users//favorites/tracks?sessionId=&countryCode=&limit=999
```


it's completely possible that the track in the source account is no longer available and hence throwing the `album not found error` but as for the err500 i'm not quite sure

**Comment by morguldir** [comment]
I can reproduce the 500 error if i try to add something that isn't a number, what does your list contain?

The 404 message probably just means that the track doesn't exist anymore, or that it's region locked.

**Comment by bkr32** [comment]
my list contains `trackID ` unless it's being read incorrectly.
i'm leaning towards the track not existing anymore (which is a shame) since even on the source account creating a playlist from favorites throws a server error

**Comment by bkr32** [comment]
i've managed to point out the missing tracks, just its just to put a try catch around them and carry on, also found the issue with read file, turns out its good ol encoding.

@bjesus if your issue has been sorted we can close the issue

**Comment by bjesus** [comment]
Indeed, just checked and apparently out of the 90 track IDs I was trying to add, one was giving a problem. I changed my script to run it track by track with a `try` around and could then find the problematic one. Thank you!
