### ISSUE TITLE
FeatureRequest: Mixes support

### ISSUE THREAD

**Issue by marrobHD** [tamland/python-tidal#62]
Example mix: https://tidal.com/browse/mix/0026376c13ae1d8f66f5fb87756217

**Comment by BlackLight** [comment]
Has there been any progress on this issue? From what I can see, it's the only one blocking the 0.7 release.

**Comment by morguldir** [comment]
> Has there been any progress on this issue? From what I can see, it's the only one blocking the 0.7 release.

I had to refresh the support for the /pages endpoints, and it works with the explore page now, so all that's left is parsing the mixes, which look pretty similar.

But the main blocker for a full 0.7.0 release has been a 0.6.x -> 0.7.x migration guide and making the documentation more complete.
