### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by pyropy** [tamland/python-tidal#63]
Hi,

When trying to login with I get following error:
```
{"status":401,"subStatus":8003,"userMessage":"Client not found"}
``` 
Subscription is active and login via web works as expected.

**Comment by xmalbertox** [comment]
Can confirm using mopidy-tidal backend, which uses this api, and receive this exact same error in the debug log.

**Comment by m0555** [comment]
Same here

**Comment by owgit** [comment]
same same :S

**Comment by morguldir** [comment]
I have now implemented OAuth support, try the `login_oauth()` or the `login_oauth_simple()` method in the [0.6.x](https://github.com/tamland/python-tidal/tree/0.6.x) or the [0.7.x](https://github.com/tamland/python-tidal/tree/0.7.x) branch. 

They output a link where you have to log in and enter a code, after you enter the code and authorize the program you will be logged in.

**Comment by bjesus** [comment]
Thank you for the quick fix @morguldir!

Is there now a way to stay logged in? It seems like the credentials aren't saved anywhere (I'm using `login_oauth_simple`), so whenever I ran my script I have to re-login. I'm using my script as an alarm clock, so it defeats the purpose if I have to manually login each time before it rings 😅

**Comment by pyropy** [comment]
Here's an example for implementation on how we could handle logins from backend side:

https://github.com/pyropy/tidal-async/blob/master/tidal_async/session.py

**Comment by morguldir** [comment]
> Is there now a way to stay logged in? It seems like the credentials aren't saved anywhere (I'm using `login_oauth_simple`), so whenever I ran my script I have to re-login. I'm using my script as an alarm clock, so it defeats the purpose if I have to manually login each time before it rings

You have to store the `token_type`, `session_id`, `access_token`, and optionally the `refresh_token` from the session object after logging in, and then you can use them with the `load_oauth_session()` method later. I'm not fully sure how the expired tokens look yet, so you might want to use the `expiry_time` datetime object to check if the access token has expired, and use `token_refresh()` if it has.

**Comment by morguldir** [comment]
I have now released v0.6.8, and i have uploaded it to PyPI. This release includes the new login method mentioned above, and should resolve this issue.

**Comment by tehkillerbee** [comment]
@bjesus Take a look at how I solved reloading the OAuth session in the Mopidy-Tidal that uses the tidalapi. https://github.com/tehkillerbee/mopidy-tidal/blob/edc9b181e4e0da32bfc9dbe4a5f073996b4e183b/mopidy_tidal/backend.py#L46

**Comment by pyropy** [comment]
@morguldir Is it somehow possible to evade the need for clicking on the link, it's not really practical to use it for production system 😓 

@bjesus @tehkillerbee Have you folks maybe found workaround over clicking to link and going trough the login process?

**Comment by bjesus** [comment]
Thanks for the help everyone.

@pyropy I've clicked the link once, and then I'm just feeding the script with variables mentioned above (`token_type`, `session_id`, `access_token`, `refresh_token`). No need to click the link then. I assume you click it once on your machine and then grab those parameters and just use them in your production environment.

**Comment by pyropy** [comment]
> Thanks for the help everyone.
> 
> @pyropy I've clicked the link once, and then I'm just feeding the script with variables mentioned above (`token_type`, `session_id`, `access_token`, `refresh_token`). No need to click the link then. I assume you click it once on your machine and then grab those parameters and just use them in your production environment.

Yeah that seems to work.

**Comment by greggilbert** [comment]
> @pyropy I've clicked the link once, and then I'm just feeding the script with variables mentioned above (`token_type`, `session_id`, `access_token`, `refresh_token`). No need to click the link then. I assume you click it once on your machine and then grab those parameters and just use them in your production environment.

FWIW the link page does have a captcha on it (I hit this while testing the other day via private browser) so that might be a sticking point in trying to fully automate this.

**Comment by sorenwacker** [comment]
Any solution to this?

**Comment by tehkillerbee** [comment]
Yes, a similar method is also outlined in this example:
https://github.com/tamland/python-tidal/issues/165#issuecomment-1668469083

The login helper functions should probably be added to python-tidal though.

**Comment by aymather** [comment]
@tehkillerbee what about refreshing the token? after a while my token expired and it made me log in using the UI again. Obviously we have to avoid token expirations. I'm assuming we just create a cron job to refresh it every once in a while, which is fine. Do you have an example of how to refresh the token?

**Comment by tehkillerbee** [comment]
@aymather Check how it is done here in [mopidy-tidal](https://github.com/tehkillerbee/mopidy-tidal/blob/6e970708a85a58c84d99fd81b030dea42ffe62b4/mopidy_tidal/backend.py#L104)

IIRC, in mopidy-tidal, the json session file is only updated once after first login. It does not get updated again.
Using this method, I have never had issues with tokens expiring or requiring a service to refresh it so I have never looked further into it.

How often do your token expire?

tidalapi provides the necessary framework to update the token [here](https://github.com/tamland/python-tidal/blob/1d2ae41967368a2ce2d0880b0d28adf5b2dbe553/tidalapi/session.py#L442). However, this is never called by load_oauth_session(), even though the function description indicates this. To me, this looks like a bug.

Ideally, the refresh token should be used when the session expires, and the json file should then be updated. I will create a new issue for this so we can investigate further.

**Comment by jozefKruszynski** [comment]
IIRC tidal tokens are set to last for 7 days as standard.
I check the expiry on every function call I make to tidal and refresh if necessary.

**Comment by tehkillerbee** [comment]
> IIRC tidal tokens are set to last for 7 days as standard.
> I check the expiry on every function call I make to tidal and refresh if necessary.

I remember an issue about this from way back. After looking further into this, it looks like we indeed refresh the token if necessary so that explains why everything works just as expected.: https://github.com/tamland/python-tidal/commit/ee120d94d897f6f6ee644fd835a35fb68942b331

However, if a JSON file is used to store the token, this should probably be updated as well...
