### ISSUE TITLE
Problems when using this library with telerik fiddler

### ISSUE THREAD

**Issue by Takoooooo** [tamland/python-tidal#64]
I have this sample code and it works nicely without Telerik Fiddler
![image](https://user-images.githubusercontent.com/53405089/115057234-7a85ed80-9eec-11eb-8218-348ff2e7381d.png)
But i would like to see all requests which the library sends so I have to use it.
First, i had to downgrade urllib because I had issues
https://stackoverflow.com/questions/66642705/why-requests-raise-this-exception-check-hostname-requires-server-hostname
Then I still get errors but I unable to solve them.
![image](https://user-images.githubusercontent.com/53405089/115057407-b02ad680-9eec-11eb-9127-e5bf6ea2915b.png)

This looks like a solution but I'm unable to find where do I need to put that parameter.I'm kinda new to python,help me please
![image](https://user-images.githubusercontent.com/53405089/115057614-f2541800-9eec-11eb-8a25-18c9969f76c2.png)

**Comment by divadsn** [comment]
Why do you even try to use a MITM proxy to see all requests when the library code is open-source?

Anyways, I would recommend you to use https://github.com/mitmproxy/mitmproxy as it takes care of all the required SSL stuff.
