### ISSUE TITLE
Is there a way to get influencers for an artist?

### ISSUE THREAD

**Issue by nickfiggins** [tamland/python-tidal#72]
Hi, I'm looking to get fetch the "influencers" section from the tidal artist page. I was wondering if there was an endpoint available from the tidal api for this? I can't seem to find any info.

I can see that there's no function for this in this wrapper currently, but curious if this is something that could potentially be implemented.

**Comment by JuniorJPDJ** [comment]
Could you please provide an example of artist which has one?
Maybe with URL and screenshot to be sure I know what you are talking about.

**Comment by nickfiggins** [comment]
Sure! Here you go:

Link: https://listen.tidal.com/artist/3503597

Image:
<img width="1792" alt="Screen Shot 2021-05-17 at 10 15 21 PM" src="https://user-images.githubusercontent.com/46427579/118580196-79e7ad80-b75d-11eb-871b-c74368286798.png">

**Comment by morguldir** [comment]
This is available in the 0.7.x branch now, `session.album(3503597).page()`, and it will be in the categories list, I didn't find an endpoint for it though, so you will have to search for it somehow
