### ISSUE TITLE
Is it possible to sort my collection albums by recently added?

### ISSUE THREAD

**Issue by dennisklad** [tamland/python-tidal#77]

**Comment by dennisklad** [comment]
I have a small python script to retrieve the albums in my collection and then write them to an excel.
My code looks like that and outputs album metadata in alphabetical order. Is there a field (date added) or a sort option to return them in recently added order?

```session.login_oauth_simple()
favorites = tidalapi.Favorites(session, session.user.id)
albums = favorites.albums()
for item in range(len(albums)):
    partist =  ' & '.join([str(art.name) for art in albums[item].artists])
    outSheet.write(item+1, 0, partist)
    outSheet.write(item+1, 1, albums[item].name)
    outSheet.write(item+1, 2, albums[item].release_date.year)
    outSheet.write(item+1, 3, albums[item].num_tracks)
    outSheet.write(item+1, 4, int(albums[item].duration/60))```

**Comment by morguldir** [comment]
Unsure why this was closed, but you should be able to use the [user_date_added](https://0-7-x--tidalapi.netlify.app/api.html#tidalapi.album.Album.user_date_added) field
