### ISSUE TITLE
How to get user_id when using load_session method?

### ISSUE THREAD

**Issue by apjavel** [tamland/python-tidal#9]
When I log in u sin session.login and putting in my username and password I get my user_id back.

But when using session.load_session I need to provided a session_id and a user_id. But I don't have the user_id in that case.

I have a renderer (from Linn). I am writing a control point for these players, using upnp. The renderer has the login details stored (username and password). The controlpoint can use upnp to make the renderer login to Tidal. The renderer then provides a session_id to the controlpoint. But for the controlpoint to load the session in tidalapi I also need the user_id, which I don't have!

Is there some way to query the Tidal api for this, providing only session_id or username?

Thanks!

**Comment by windhamwong** [comment]
There is no easy to get it, but you can try to get it by going to capture packets from the browser, and click on settings, you will see the ID there.
Or you can do `session.user.id` as well
