### ISSUE TITLE
Can't create new sessions

### ISSUE THREAD

**Issue by sterni1971** [tamland/python-tidal#95]
Today my mopidy-tidal stopped. Itried to create a new session but there seems to be a
problem with tidal?

root@pi:~# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tidalapi
>>> session = tidalapi.Session()
>>> session.login_oauth_simple()
Login failed: {"status":401,"error":"invalid_client","error_description":"Client with token 8SEZWa4J1NVC5U5Y not found","sub_status":1005}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 213, in login_oauth_simple
    login, future = self.login_oauth()
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 226, in login_oauth
    login, future = self._login_with_link()
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 240, in _login_with_link
    request.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://auth.tidal.com/v1/oauth2/device_authorization

**Comment by 2e0byo** [comment]
Looks like the secrets have been rotated again... this has bitten me as well.  I guess we have to wait for someone with working 'official' hardware and a network sniffer to intercept the new secrets.

**Comment by 2e0byo** [comment]
The client_id and client_secret in [this comment](https://github.com/yaronzz/Tidal-Media-Downloader/issues/797#issuecomment-1015617361) work for me.  @sterni1971 you can set them directly in your mopidy config file until this project is updated.

**Comment by 2e0byo** [comment]
See also https://gist.github.com/charleywright/59c14e083177619d8cc9630d7f468690 which may be of interest.

**Comment by dennisklad** [comment]
I also encountered the same error today. Can I do something manually to fix this or should I just wait until its fixed in the new release?

**Comment by chicco64** [comment]
it's the same for me too

**Comment by Carioca** [comment]
> The client_id and client_secret in [this comment](https://github.com/yaronzz/Tidal-Media-Downloader/issues/797#issuecomment-1015617361) work for me. @sterni1971 you can set them directly in your mopidy config file until this project is updated. Note that this is a master only key, sadly.

I've been managing to create sessions with this, and they played music for about a day, now I get all kinds of 401s on my mopidy output

**Comment by 1nikolas** [comment]
> Looks like the secrets have been rotated again... this has bitten me as well. I guess we have to wait for someone with working 'official' hardware and a network sniffer to intercept the new secrets.

I found some by reverse engineering the android app. The TV one should work fine with this. Here are them all
https://gist.github.com/charleywright/59c14e083177619d8cc9630d7f468690?permalink_comment_id=4054789#gistcomment-4054789

**Comment by trumpeta** [comment]
I've lead into the same issue using the testsample code

```
import tidalapi
session = tidalapi.Session()
session.login_oauth_simple()
tracks = session.get_album_tracks(album_id=16909093)
for track in tracks:
    print(track.name)
```

At the login call I get the response from server

Login failed: {"status":401,"error":"invalid_client","sub_status":1005,"error_description":"Client with token 8SEZWa4J1NVC5U5Y not found"}

**Comment by morguldir** [comment]
@1nikolas Thanks, i ended up using one of the secrets you linked.

The new secret is used in version 0.6.10 and should now work again.
