### ISSUE TITLE
Feature suggestion: add tracks to favorites or to playlist using list of ISRC's

### ISSUE THREAD

**Issue by Steve-Z** [tamland/python-tidal#96]
Rather than matching a track using a track name +/- album +/- artist, why not match on ISRC which, if I understand those correctly, are a universal unique identifier for tracks? That would speed up the process since it could bypass the search API. I am specifically interested in this because it would greatly simplify my import of Spotify "Liked Songs" or any of my playlists. Using the Spotify API it is relatively simple to extract ISRC's for each track.

**Comment by morguldir** [comment]
Would be nice, but I'm not aware of any ways to use ISRC's for that, but you can use it to find the correct result when searching at least.

**Comment by Steve-Z** [comment]
Thanks @morguldir. As I have dug into the competing platforms a bit, my observation is that they make their APIs unnecessarily proprietary and complex; I am guessing there is a biz model angle to that (adding "switching costs"). 

Spotify, despite its other numerous shortcomings, does have a fairly open and transparent API. Tidal, not so much, and Apple probably the worst (you can see some of it but cannot access anything without paying!). I think user/dev experience takes a far-back seat to revenues.

**Comment by timrae** [comment]
They have a new public API with an endpoint similar to what's being requested here. The direct link doesn't work but search for "Get tracks by ISRC" here:  https://apiref.developer.tidal.com

**Comment by tehkillerbee** [comment]
Added in https://github.com/tamland/python-tidal/pull/288
